Repository kokkos/kokkos-kernels, pull requests merged in 2019-12, with the labels that each got.

#502 Gauss-Seidel: rank-2 X/Y support
  src/common/KokkosKernels_Handle.hpp
  src/common/KokkosKernels_Utils.hpp
  src/sparse/KokkosSparse_gauss_seidel.hpp
  src/sparse/KokkosSparse_gauss_seidel_handle.hpp
  src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_spec.hpp
  unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
  unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Labels: enhancement

#515 Test sequential SOR (#494)
  unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Labels: enhancement

#522 KokkosKernelsConfig.cmake fixes for TPLs
  cmake/Modules/FindTPLCUSPARSE.cmake
  cmake/kokkoskernels_tpls.cmake
Labels: bug

#524 Fix DotBasedGEMM bug encountered in Trilinos issue 6418
  src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
  unit_test/blas/Test_Blas3_gemm.hpp
Labels: bug fixed-in-develop

#536 Fixed pthread definitions for gtest
  unit_test/CMakeLists.txt
Labels: bug

#550 Fix fallback gemm for complex scalar types
  src/blas/impl/KokkosBlas3_gemm_impl.hpp
  unit_test/blas/Test_Blas3_gemm.hpp
Labels: bug fixed-in-develop

#549 Fix spgemm memory pool leaks, minor memory bugs
  src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp
Labels: bug

#507 SpMV tests: fixing the logic to detect the level of precision needed
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: bug

#553 Add the conjugate transpose support to DotBasedGEMM
  src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
Labels: enhancement
