Repository kokkos/kokkos-kernels, pull requests merged in 2020-08, with the labels that each got.

#764 Use relative errors in the spgemm and jacobi tests
  src/common/KokkosKernels_SimpleUtils.hpp
  unit_test/sparse/Test_Sparse_spgemm.hpp
  unit_test/sparse/Test_Sparse_spgemm_jacobi.hpp
Labels: enhancement

#779 Remove bash error from cm_generate_makefile
  cm_generate_makefile.bash
Labels: enhancement

#781 Fix the relative error computation (used in SpGEMM and Jacobi-fused SpGEMM tests)
  src/common/KokkosKernels_SimpleUtils.hpp
Labels: bug fixed-in-develop

#782 Add new SpGEMM interfaces to the unit tests
  src/sparse/impl/KokkosSparse_spgemm_numeric_spec.hpp
  unit_test/sparse/Test_Sparse_spgemm.hpp
Labels: enhancement, feature request
