Repository kokkos/kokkos-kernels, pull requests merged in 2020-10, with the labels that each got.

#827 Factor out coarsening
  src/common/KokkosKernels_SparseUtils.hpp
  src/graph/KokkosGraph_ExplicitCoarsening.hpp
  src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
  src/graph/impl/KokkosGraph_ExplicitCoarsening_impl.hpp
  src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp
Labels: enhancement

#804 cuSPARSE 11: fix spgemm and spmv_struct_tunning, see issue #803
  perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp
  src/sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_def.hpp
Labels: Cleanup

#831 Test spmv transpose (Fix #829)
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: enhancement

#834 Add fallback condition to use spmv_native when cuSPARSE won't work
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  src/sparse/KokkosSparse_spmv.hpp
  src/sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp
  src/sparse/impl/KokkosSparse_spmv_spec.hpp
  src/sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: bug, enhancement

#823 Allow enabling/disabling certain components
  CMakeLists.txt
  cmake/fake_tribits.cmake
  cmake/kokkoskernels_tribits.cmake
  perf_test/CMakeLists.txt
  perf_test/batched/CMakeLists.txt
  perf_test/blas/CMakeLists.txt
  perf_test/blas/blas/CMakeLists.txt
  perf_test/blas/blas3/CMakeLists.txt
  perf_test/performance/CMakeLists.txt
  src/CMakeLists.txt
  src/kokkoskernels_eti.cmake
  unit_test/CMakeLists.txt
Labels: WIP

#840 HIP: fixing a couple of issues on AMD
  src/common/KokkosKernels_BitUtils.hpp
  src/sparse/KokkosSparse_CrsMatrix.hpp
Labels: bug develop-only
