Repository kokkos/kokkos-kernels, pull requests merged in 2020-07, with the labels that each got.

#731 First iteration of HashmapAccumulator cleanup
  perf_test/sparse/KokkosSparse_run_spgemm.hpp
  src/common/KokkosKernels_HashmapAccumulator.hpp
  src/common/KokkosKernels_Utils.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_seq.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_triangle_no_compression.hpp
  src/sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
  src/sparse/impl/KokkosSparse_spgemm_symbolic_spec.hpp
  unit_test/sparse/Test_Sparse_spgemm.hpp
Labels: Cleanup

#771 Backport cusparse tpl spmv changes from Trilinos
  example/wiki/sparse/KokkosSparse_wiki_gauss_seidel.cpp
  src/common/KokkosKernels_Controls.hpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  src/sparse/KokkosSparse_spmv.hpp
  src/sparse/impl/KokkosSparse_spmv_spec.hpp
Labels: bug, enhancement

#774 Shrink size of block GS test matrix
  unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
Labels: enhancement

#773 Cleanup spadd (#685, #694)
  perf_test/sparse/KokkosSparse_run_spadd.hpp
  src/sparse/KokkosSparse_spadd.hpp
  src/sparse/KokkosSparse_spadd_handle.hpp
  unit_test/sparse/Test_Sparse_spadd.hpp
Labels: enhancement
