Repository kokkos/kokkos-kernels, pull requests merged in 2020-06, with the labels that each got.

#733 Fix divide by zero in sort_crs_matrix, for 0 rows
  src/common/KokkosKernels_SparseUtils.hpp
Labels: bug

#734 TRMM and TRTRI perf test bug fixes and improvements
  perf_test/blas/blas/KokkosBlas_perf_test.cpp
  perf_test/blas/blas/KokkosBlas_trtri_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas3_perf_test.cpp
  perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp
Labels: bug, enhancement

#725 Kokkos::Controls and cusparse merge algorithm, see issue #670
  cmake/kokkoskernels_tpls.cmake
  perf_test/sparse/CMakeLists.txt
  perf_test/sparse/KokkosSparse_spmv_merge.cpp
  src/CMakeLists.txt
  src/common/KokkosKernels_Controls.hpp
  src/common/KokkosKernels_IOUtils.hpp
  src/impl/tpls/KokkosKernels_tpl_handles.cpp
  src/impl/tpls/KokkosKernels_tpl_handles_decl.hpp
  src/impl/tpls/KokkosKernels_tpl_handles_def.hpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  src/sparse/KokkosSparse_spmv.hpp
  src/sparse/impl/KokkosSparse_spmv_impl.hpp
  src/sparse/impl/KokkosSparse_spmv_spec.hpp
  src/sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: enhancement

#737 Wiki examples: tests added
  CMakeLists.txt
  cm_generate_makefile.bash
  example/CMakeLists.txt
  example/wiki/CMakeLists.txt
  example/wiki/sparse/CMakeLists.txt
  example/wiki/sparse/KokkosSparse_wiki_crsmatrix.cpp
  example/wiki/sparse/KokkosSparse_wiki_spmv.cpp
Labels: Documentation, enhancement

#742 Using structured matrix in wiki spmv example
  example/wiki/sparse/CMakeLists.txt
  example/wiki/sparse/KokkosSparse_wiki_spmv.cpp
  test_common/KokkosKernels_Test_Structured_Matrix.hpp
Labels: Cleanup

#745 Allow const-valued C rowmap in spgemm/add numeric (Fix #744)
  src/sparse/KokkosSparse_spadd.hpp
  src/sparse/KokkosSparse_spgemm_numeric.hpp
Labels: bug

#748 Added GS and coloring examples.
  example/wiki/CMakeLists.txt
  example/wiki/graph/CMakeLists.txt
  example/wiki/graph/KokkosGraph_wiki_coloring.cpp
  example/wiki/sparse/CMakeLists.txt
  example/wiki/sparse/KokkosSparse_wiki_gauss_seidel.cpp
  src/common/KokkosKernels_IOUtils.hpp
Labels: enhancement

#743 Simplified SpADD/SpGEMM interface
  example/wiki/sparse/CMakeLists.txt
  example/wiki/sparse/KokkosSparse_wiki_spadd.cpp
  example/wiki/sparse/KokkosSparse_wiki_spgemm.cpp
  example/wiki/sparse/KokkosSparse_wiki_spmv.cpp
  src/sparse/KokkosSparse_spadd.hpp
  src/sparse/KokkosSparse_spgemm.hpp
  src/sparse/KokkosSparse_spgemm_numeric.hpp
Labels: enhancement

#753 scripts/cm_test_all_sandia: Disable failing toolchains
  scripts/cm_test_all_sandia
Labels: Cleanup

#752 Install KokkosKernels_default_types.hpp to include/
  src/common/KokkosKernels_default_types.hpp
Labels: bug

#755 Fix time reporting in SPMV merge-path test: don't scale times by 0.001
  perf_test/sparse/KokkosSparse_spmv_merge.cpp
Labels: bug
