Repository kokkos/kokkos-kernels, pull requests merged in 2020-03, with the labels that each got.

#623 Dist2 initial improvements
  perf_test/graph/KokkosGraph_color.cpp
  perf_test/graph/KokkosGraph_color_d2.cpp
  src/graph/KokkosGraph_Distance1Color.hpp
  src/graph/KokkosGraph_Distance2Color.hpp
  src/graph/KokkosGraph_Distance2ColorHandle.hpp
  src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
  src/graph/impl/KokkosGraph_Distance2Color_impl.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_color.hpp
  unit_test/graph/Test_Graph_graph_color_distance2.hpp
Labels: bug, enhancement

#630 Small clean-up in spgemm and sptrsv for clang 7 cuda build with tpls
  src/sparse/KokkosSparse_spgemm_handle.hpp
  src/sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp
  src/sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp
Labels: bug

#638 Fixed D2 resolveConflictsSerial() memory safety (#634)
  src/graph/impl/KokkosGraph_Distance2Color_impl.hpp
Labels: bug

#646 Fix UVM errors (generally, missing fences) in several places
  scripts/cm_test_all_sandia
  src/sparse/KokkosSparse_sptrsv_handle.hpp
  src/sparse/impl/KokkosSparse_spiluk_numeric_impl.hpp
  src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
  src/sparse/impl/KokkosSparse_sptrsv_symbolic_impl.hpp
  test_common/Test_Common_Sorting.hpp
  unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
  unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Labels: bug

#618 Spmv cusparse tpl
  perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  src/sparse/impl/KokkosSparse_spmv_spec.hpp
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: enhancement

#649 Fixed block row formula in block GS test (Fix #648)
  unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
Labels: bug

#554 Add TPL support for CBLAS and LAPACKE
  cmake/Modules/FindTPLCBLAS.cmake
  cmake/Modules/FindTPLCHOLMOD.cmake
  cmake/Modules/FindTPLLAPACKE.cmake
  cmake/Modules/FindTPLSUPERLU.cmake
  cmake/kokkoskernels_tpls.cmake
  cmake/kokkoskernels_tribits.cmake
  scripts/cm_test_all_sandia
  src/CMakeLists.txt
Labels: WIP

#622 Initial support for trmm and trtri
  Makefile.kokkos-kernels
  src/blas/KokkosBlas3_trmm.hpp
  src/blas/KokkosBlas_trtri.hpp
  src/blas/impl/KokkosBlas3_trmm_spec.hpp
  src/blas/impl/KokkosBlas_trtri_spec.hpp
  src/impl/tpls/KokkosBlas3_trmm_tpl_spec_avail.hpp
  src/impl/tpls/KokkosBlas3_trmm_tpl_spec_decl.hpp
  src/impl/tpls/KokkosBlas_Host_tpl.cpp
  src/impl/tpls/KokkosBlas_Host_tpl.hpp
  src/impl/tpls/KokkosBlas_tpl_spec.hpp
  src/impl/tpls/KokkosBlas_trtri_tpl_spec_avail.hpp
  src/impl/tpls/KokkosBlas_trtri_tpl_spec_decl.hpp
  unit_test/Makefile
  unit_test/blas/Test_Blas3_trmm.hpp
  unit_test/blas/Test_Blas_trtri.hpp
  unit_test/cuda/Test_Cuda_Blas3_trmm.cpp
  unit_test/cuda/Test_Cuda_Blas_trtri.cpp
  unit_test/openmp/Test_OpenMP_Blas3_trmm.cpp
  unit_test/openmp/Test_OpenMP_Blas_trtri.cpp
Labels: feature request

#643 Adding utitly functions and macro to catch cusparse errors and implementing transpose mode, see #614 and #650
  src/common/KokkosKernels_SparseUtils_cusparse.hpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  unit_test/CMakeLists.txt
  unit_test/cuda/Test_Cuda_Sparse_Utils_cusparse.cpp
  unit_test/sparse/Test_Sparse_Utils_cusparse.hpp
Labels: enhancement

#661 Fix624: lots of distance-2 changes, fix Utils transpose
  perf_test/graph/KokkosGraph_color_d2.cpp
  src/common/KokkosKernels_IOUtils.hpp
  src/common/KokkosKernels_SparseUtils.hpp
  src/graph/KokkosGraph_Distance2Color.hpp
  src/graph/KokkosGraph_Distance2ColorHandle.hpp
  src/graph/impl/KokkosGraph_Distance2Color_MatrixSquared_impl.hpp
  src/graph/impl/KokkosGraph_Distance2Color_impl.hpp
  test_common/KokkosKernels_TestParameters.hpp
  unit_test/graph/Test_Graph_graph_color_distance2.hpp
Labels: bug, enhancement

#663 Test transpose util, add CRS sorting util
  perf_test/sparse/KokkosSparse_gs.cpp
  perf_test/sparse/KokkosSparse_spgemm.cpp
  perf_test/sparse/KokkosSparse_spiluk.cpp
  perf_test/sparse/KokkosSparse_spmv.cpp
  perf_test/sparse/KokkosSparse_spmv_struct.cpp
  perf_test/sparse/KokkosSparse_sptrsv.cpp
  src/common/KokkosKernels_SparseUtils.hpp
  src/common/KokkosKernels_Utils.hpp
  src/graph/KokkosGraph_Distance2Color.hpp
  src/sparse/KokkosSparse_spadd.hpp
  test_common/KokkosKernels_default_types.hpp
  test_common/Test_Common_Sorting.hpp
  test_common/Test_Common_Transpose.hpp
  unit_test/cuda/Test_Cuda_Common_Transpose.cpp
  unit_test/graph/Test_Graph_graph_color_distance2.hpp
  unit_test/openmp/Test_OpenMP_Common_Transpose.cpp
  unit_test/serial/Test_Serial_Common_Transpose.cpp
  unit_test/threads/Test_Threads_Common_Transpose.cpp
Labels: enhancement
