Repository kokkos/kokkos-kernels, pull requests merged in 2020-04, with the labels that each got.

#679 Fix and clean up spgemm color
  src/sparse/KokkosSparse_spgemm_handle.hpp
  src/sparse/KokkosSparse_spgemm_numeric.hpp
  src/sparse/KokkosSparse_spgemm_symbolic.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_color.hpp
Labels: Cleanup, bug

#681 Fix Issue #678: kk_generate_diagonally_dominant_sparse_matrix
  src/common/KokkosKernels_IOUtils.hpp
Labels: bug fixed-in-develop

#698 Intel 17 bug workaround, fix team QR random failure, fix several warnings
  perf_test/sparse/KokkosSparse_spgemm.cpp
  perf_test/sparse/KokkosSparse_spgemm_jacobi.cpp
  perf_test/sparse/KokkosSparse_spmv_struct.cpp
  perf_test/sparse/KokkosSparse_sptrsv_superlu.cpp
  src/batched/KokkosBatched_Eigendecomposition_Serial_Internal.hpp
  src/batched/KokkosBatched_Householder_TeamVector_Internal.hpp
  src/batched/KokkosBatched_Vector_SIMD.hpp
  src/batched/KokkosBatched_Vector_SIMD_Arith.hpp
  src/blas/impl/KokkosBlas3_gemm_impl.hpp
  src/common/KokkosKernels_Macros.hpp
  test_common/Test_Common_Sorting.hpp
  unit_test/batched/Test_Batched_TeamVectorQR.hpp
Labels: CompilerIssue, WIP, bug

#706 Fix705: load module environment in reproducer script
  scripts/cm_test_all_sandia
Labels: enhancement

#708 Fix 703: correct CrsMatrix documentation
  src/sparse/KokkosSparse_CrsMatrix.hpp
Labels: Cleanup, Documentation

#709 Fix module environment setup in cm_test_all_sandia
  scripts/cm_test_all_sandia
Labels: bug
