Repository kokkos/kokkos-kernels, pull requests merged in 2021-07, with the labels that each got.

#1038 Adding ArmPL option to spmv perf_test
  perf_test/sparse/KokkosSparse_spmv.cpp
  perf_test/sparse/spmv/ArmPL_SPMV.hpp
  perf_test/sparse/spmv/KokkosKernels_spmv_data.hpp
Labels: enhancement

#1042 Fix559: Intel 18 has trouble with pointer in ternary expr
  src/blas/impl/KokkosBlas3_trsm_impl.hpp
Labels: CompilerIssue

#1022 perf_test/blas/blas3: Fixes for armpl dgemm
  perf_test/blas/blas3/KokkosBlas3_common.hpp
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas3_perf_test.cpp
Labels: bug develop-only, enhancement

#1028 Adding Kokkos GMRES example.
  example/CMakeLists.txt
  example/gmres/CMakeLists.txt
  example/gmres/README.md
  example/gmres/ex_real_A.cpp
  example/gmres/gmres.hpp
  example/gmres/test_cmplx_A.cpp
  example/gmres/test_real_A.cpp
Labels: enhancement

#1063 Updates to GMRES example.
  example/gmres/README.md
  example/gmres/ex_real_A.cpp
  example/gmres/gmres.hpp
  example/gmres/test_cmplx_A.cpp
  example/gmres/test_real_A.cpp
Labels: enhancement

#1070 KokkosKernels_ExecSpaceUtils: kk_is_a64fx_mem_space add brace
  src/common/KokkosKernels_ExecSpaceUtils.hpp
Labels: bug, bug develop-only
