Repository kokkos/kokkos-kernels, pull requests merged in 2021-03, with the labels that each got.

#910 Small but important fixes and testing coverage (mainly in graph coarsening)
  src/graph/KokkosGraph_Distance1ColorHandle.hpp
  src/graph/KokkosGraph_Distance2ColorHandle.hpp
  src/graph/KokkosGraph_ExplicitCoarsening.hpp
  src/graph/KokkosGraph_MIS2.hpp
  unit_test/graph/Test_Graph_mis2.hpp
Labels: bug

#899 Supernodal SpTRSV, improve symbolic performance
  src/sparse/KokkosSparse_sptrsv.hpp
  src/sparse/KokkosSparse_sptrsv_superlu.hpp
  src/sparse/KokkosSparse_sptrsv_supernode.hpp
  src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
  src/sparse/impl/KokkosSparse_sptrsv_symbolic_impl.hpp
Labels: AT: STALE

#915 Fixed nrm1 (#914), removed cublas nrminf, improved blas tests
  src/blas/impl/KokkosBlas1_nrm1_impl.hpp
  src/impl/tpls/KokkosBlas1_nrminf_tpl_spec_avail.hpp
  src/impl/tpls/KokkosBlas1_nrminf_tpl_spec_decl.hpp
  test_common/KokkosKernels_TestUtils.hpp
  unit_test/blas/Test_Blas1_abs.hpp
  unit_test/blas/Test_Blas1_asum.hpp
  unit_test/blas/Test_Blas1_axpby.hpp
  unit_test/blas/Test_Blas1_axpy.hpp
  unit_test/blas/Test_Blas1_dot.hpp
  unit_test/blas/Test_Blas1_iamax.hpp
  unit_test/blas/Test_Blas1_mult.hpp
  unit_test/blas/Test_Blas1_nrm1.hpp
  unit_test/blas/Test_Blas1_nrm2.hpp
  unit_test/blas/Test_Blas1_nrm2_squared.hpp
  unit_test/blas/Test_Blas1_nrminf.hpp
  unit_test/blas/Test_Blas1_reciprocal.hpp
  unit_test/blas/Test_Blas1_scal.hpp
  unit_test/blas/Test_Blas1_sum.hpp
  unit_test/blas/Test_Blas1_team_dot.hpp
  unit_test/blas/Test_Blas1_team_nrm2.hpp
  unit_test/blas/Test_Blas1_team_scal.hpp
  unit_test/blas/Test_Blas1_team_update.hpp
  unit_test/blas/Test_Blas1_update.hpp
  unit_test/blas/Test_Blas2_gemv.hpp
  unit_test/blas/Test_Blas2_team_gemv.hpp
  unit_test/blas/Test_Blas3_gemm.hpp
  unit_test/blas/Test_Blas3_trmm.hpp
  unit_test/blas/Test_Blas3_trsm.hpp
Labels: bug, enhancement

#913 perf_test/blas/blas3: Fix device verify
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
  src/batched/KokkosBatched_Vector_SIMD.hpp
Labels: bug

#918 Fix #917: ctor CrsMat mirror with CrsGraph mirror
  src/sparse/KokkosSparse_CrsMatrix.hpp
  unit_test/sparse/Test_Sparse_CrsMatrix.hpp
Labels: bug, enhancement
