Repository kokkos/kokkos-kernels, pull requests merged in 2021-02, with the labels that each got.

#883 Construct SpGEMM C with correct #cols
  src/sparse/KokkosSparse_spgemm.hpp
Labels: bug

#884 Fixed supernodal SpTRSV build with serial+openmp+cuda
  src/sparse/KokkosSparse_sptrsv_handle.hpp
  src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
Labels: bug

#860 Adding a smoke test using some CMake logic
  CMakeLists.txt
  install_test/CMakeLists.txt
  install_test/CMakeLists.txt.in
  install_test/run_install_test.sh.in
  perf_test/sparse/KokkosSparse_block_pcg.cpp
Labels: enhancement, feature request

#885 Make work_view_t typedef consistent
  src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
Labels: AT: STALE

#895 Add MKL SpMV wrapper
  src/impl/KokkosKernels_helpers.hpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  src/sparse/KokkosSparse_spmv.hpp
Labels: enhancement

#893 Serial code path for spmv
  src/sparse/impl/KokkosSparse_spmv_impl.hpp
Labels: enhancement
