Repository kokkos/kokkos-kernels, pull requests merged in 2021-12, with the labels that each got.

#1208 example/gmres: Specify half_t namespace
  example/gmres/gmres.hpp
  example/gmres/test_cmplx_A.cpp
Labels: bug develop-only

#1229 Improve graph color perf test
  perf_test/graph/KokkosGraph_color.cpp
Labels: enhancement

#1221 SpMV: adding support for rocSPARSE TPL
  src/common/KokkosKernels_Controls.hpp
  src/common/KokkosKernels_SparseUtils_rocsparse.hpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  src/sparse/KokkosSparse_spmv.hpp
Labels: enhancement, feature request, AT: STALE
