Repository kokkos/kokkos-kernels, pull requests merged in 2021-06, with the labels that each got.

#1007 cmake/Modules: Allow user to use MAGMA_DIR from env
  cmake/Modules/FindTPLMAGMA.cmake
Labels: enhancement

#997 Supernodal SpTRSV: update TPLs requirements
  cmake/kokkoskernels_features.cmake
  src/sparse/KokkosSparse_sptrsv_cholmod.hpp
  src/sparse/KokkosSparse_sptrsv_superlu.hpp
  src/sparse/KokkosSparse_sptrsv_supernode.hpp
  src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
  src/sparse/impl/KokkosSparse_sptrsv_symbolic_impl.hpp
  unit_test/sparse/Test_Sparse_sptrsv.hpp
Labels: bug

#1013 SpTRSV: removing the call with unused parameters to check_cusparse
  perf_test/sparse/KokkosSparse_sptrsv_aux.hpp
Labels: bug

#1014 scripts/cm_test_all_sandia: Fix CUDA module lists
  scripts/cm_test_all_sandia
Labels: CompilerIssue, bug

#1005 perf_test/blas/blas3: Add dgemm armpl experiment
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
Labels: AT: STALE, feature request

#1004 Fix nightly build errors in KokkosBlas3_Gemm_impl.hpp
  src/KokkosKernels_Macros.hpp
Labels: AT: STALE, bug

#1008 Some fixes for MAGMA TPL and gesv
  src/blas/KokkosBlas_gesv.hpp
  src/blas/impl/KokkosBlas_gesv_spec.hpp
  src/impl/tpls/KokkosBlas_tpl_spec.hpp
  unit_test/blas/Test_Blas_gesv.hpp
Labels: bug
