Repository kokkos/kokkos-kernels, pull requests merged in 2021-01, with the labels that each got.

#872 Fix >1024 team size error in sort_crs_*
  src/common/KokkosKernels_SparseUtils.hpp
  test_common/Test_Common_Sorting.hpp
Labels: bug

#871 Fixing seg fault with empty matrix in kspiluk
  src/sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
Labels: bug

#875 Move spmv fallback branch out of TPL layer
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  src/sparse/KokkosSparse_spmv.hpp
Labels: bug

#878 IntelClang guarding __assume_aligned with !defined(__clang__)
  perf_test/sparse/spmv/OpenMPSmartStatic_SPMV.hpp
  src/sparse/impl/KokkosSparse_spmv_impl_omp.hpp
Labels: Cleanup, CompilerIssue

#882 Matrix Converter: fixing issue with deallocation after Kokkos::fininalize()
  test_common/KokkosKernels_MatrixConverter.cpp
Labels: Cleanup
