Repository kokkos/kokkos-kernels, pull requests merged in 2021-05, with the labels that each got.

#948 GEMM: call GEMV instead in certain cases
  perf_test/blas/blas3/CMakeLists.txt
  perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test.cpp
  src/blas/KokkosBlas3_gemm.hpp
  unit_test/blas/Test_Blas3_gemm.hpp
Labels: enhancement

#930 SpAdd performance improvements, better perf test, fix mtx reader columns
  perf_test/sparse/KokkosSparse_run_spadd.hpp
  perf_test/sparse/KokkosSparse_spadd.cpp
  src/common/KokkosKernels_IOUtils.hpp
  src/sparse/KokkosSparse_spadd.hpp
  src/sparse/KokkosSparse_spadd_handle.hpp
  test_common/KokkosKernels_TestParameters.hpp
Labels: enhancement

#932 Move sorting functionality out of Impl::
  perf_test/graph/KokkosGraph_run_triangle.hpp
  perf_test/sparse/KokkosSparse_multimem_spgemm.hpp
  perf_test/sparse/KokkosSparse_run_spgemm.hpp
  perf_test/sparse/KokkosSparse_run_spgemm_jacobi.hpp
  src/common/KokkosKernels_Sorting.hpp
  src/common/KokkosKernels_SparseUtils.hpp
  src/graph/KokkosGraph_ExplicitCoarsening.hpp
  src/sparse/KokkosSparse_spadd.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  src/sparse/impl/KokkosSparse_twostage_gauss_seidel_impl.hpp
  test_common/KokkosKernels_MatrixConverter.cpp
  unit_test/common/Test_Common_Sorting.hpp
  unit_test/common/Test_Common_Transpose.hpp
  unit_test/sparse/Test_Sparse_spgemm.hpp
  unit_test/sparse/Test_Sparse_spgemm_jacobi.hpp
Labels: enhancement

#954 Deprecation: a deprecated function is called in the SpADD perf_test
  perf_test/sparse/KokkosSparse_spadd.cpp
Labels: Cleanup

#964 Fix -Werror=deprecated errors with c++20 standard
  src/blas/impl/KokkosBlas2_gemv_impl.hpp
  src/sparse/KokkosSparse_spadd.hpp
Labels: Cleanup

#961 Fix invalid mem accesses in new GEMV kernel
  src/blas/impl/KokkosBlas2_gemv_impl.hpp
  test_common/KokkosKernels_TestUtils.hpp
  unit_test/blas/Test_Blas2_gemv.hpp
Labels: bug

#970 Warning: unused-parameter warning generates error in nightly builds
  src/sparse/impl/KokkosSparse_spgemm_imp_outer.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
  src/sparse/impl/KokkosSparse_spgemm_mkl2phase_impl.hpp
Labels: Cleanup

#965 Fix build and add CI coverage for LayoutLeft=OFF
  scripts/cm_test_all_sandia
  src/blas/KokkosBlas1_axpby.hpp
  src/blas/KokkosBlas1_dot.hpp
  src/blas/KokkosBlas1_iamax.hpp
  src/blas/KokkosBlas1_mult.hpp
  src/blas/KokkosBlas1_nrm1.hpp
  src/blas/KokkosBlas1_nrm2.hpp
  src/blas/KokkosBlas1_nrm2_squared.hpp
  src/blas/KokkosBlas1_nrminf.hpp
  src/blas/KokkosBlas1_scal.hpp
  src/blas/KokkosBlas1_sum.hpp
  src/blas/KokkosBlas2_gemv.hpp
  src/blas/impl/KokkosBlas1_axpby_spec.hpp
  src/blas/impl/KokkosBlas1_dot_spec.hpp
  src/blas/impl/KokkosBlas1_iamax_spec.hpp
  src/blas/impl/KokkosBlas1_mult_spec.hpp
  src/blas/impl/KokkosBlas1_nrm1_spec.hpp
  src/blas/impl/KokkosBlas1_nrm2_spec.hpp
  src/blas/impl/KokkosBlas1_nrminf_spec.hpp
  src/blas/impl/KokkosBlas1_scal_spec.hpp
  src/blas/impl/KokkosBlas1_sum_spec.hpp
  src/blas/impl/KokkosBlas2_gemv_spec.hpp
  src/common/KokkosKernels_Handle.hpp
  src/impl/KokkosKernels_helpers.hpp
  src/impl/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp
  src/sparse/KokkosSparse_CrsMatrix.hpp
  src/sparse/KokkosSparse_gauss_seidel_handle.hpp
  src/sparse/KokkosSparse_spmv.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_spec.hpp
  src/sparse/impl/KokkosSparse_spgemm_mkl2phase_impl.hpp
  unit_test/blas/Test_Blas1_dot.hpp
  unit_test/blas/Test_Blas1_iamax.hpp
  unit_test/blas/Test_Blas1_mult.hpp
  unit_test/blas/Test_Blas1_nrm1.hpp
  unit_test/blas/Test_Blas1_nrm2.hpp
  unit_test/blas/Test_Blas1_nrminf.hpp
  unit_test/blas/Test_Blas1_scal.hpp
  unit_test/blas/Test_Blas1_sum.hpp
  unit_test/blas/Test_Blas2_gemv.hpp
  unit_test/blas/Test_Blas_gesv.hpp
  unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
  unit_test/sparse/Test_Sparse_gauss_seidel.hpp
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: bug, feature request

#993 Point multicolor GS: faster handling of long/bulk rows
  perf_test/sparse/CMakeLists.txt
  perf_test/sparse/KokkosSparse_gs.cpp
  src/common/KokkosKernels_Handle.hpp
  src/sparse/KokkosSparse_gauss_seidel_handle.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  test_common/KokkosKernels_TestUtils.hpp
  unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
  unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Labels: enhancement
