Repository kokkos/kokkos-kernels, pull requests merged in 2021-04, with the labels that each got.

#936 Kokkos_ArithTraits.hpp: Fix isInf and isNan with complex types
  src/Kokkos_ArithTraits.hpp
Labels: BlocksPromotion

#937 Prevent redundant spmv kernel instantiations (reduce library size)
  src/sparse/impl/KokkosSparse_spmv_impl.hpp
Labels: enhancement

#886 OpenMPTarget: adding ETI and CMake logic for OpenMPTarget backend
  cmake/KokkosKernelsConfig.cmake.in
  cmake/KokkosKernels_config.h.in
  cmake/kokkos_backends.cmake
  cmake/kokkoskernels_eti_devices.cmake
  perf_test/blas/blas/KokkosBlas_trtri_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp
  src/common/KokkosKernels_default_types.hpp
  unit_test/CMakeLists.txt
  unit_test/batched/Test_Batched_VectorArithmatic.hpp
  unit_test/batched/Test_Batched_VectorLogical.hpp
  unit_test/batched/Test_Batched_VectorMath.hpp
  unit_test/batched/Test_Batched_VectorMisc.hpp
  unit_test/batched/Test_Batched_VectorRelation.hpp
  unit_test/batched/Test_Batched_VectorView.hpp
  unit_test/openmptarget/Test_OpenMPTarget.hpp
  unit_test/openmptarget/Test_OpenMPTarget_Batched.cpp
  unit_test/openmptarget/Test_OpenMPTarget_Blas.cpp
  unit_test/openmptarget/Test_OpenMPTarget_Common.cpp
  unit_test/openmptarget/Test_OpenMPTarget_Graph.cpp
  unit_test/openmptarget/Test_OpenMPTarget_Sparse.cpp
Labels: feature request

#940 host only macro: adding macro to checks for any device backend
  cmake/KokkosKernels_config.h.in
  unit_test/cuda/Test_Cuda_Batched.cpp
Labels: Cleanup, enhancement

#939 Add fast two-level mode N GEMV (#926)
  perf_test/blas/CMakeLists.txt
  perf_test/blas/blas2/CMakeLists.txt
  perf_test/blas/blas2/KokkosBlas2_gemv_perf_test.cpp
  src/blas/impl/KokkosBlas2_gemv_impl.hpp
  src/blas/impl/KokkosBlas2_gemv_spec.hpp
  unit_test/blas/Test_Blas2_gemv.hpp
Labels: enhancement

#943 unit_test/batched: Remove *_half fns from gemm unit tests
  unit_test/batched/Test_Batched_SerialGemm.hpp
  unit_test/batched/Test_Batched_SerialGemm_Real.hpp
  unit_test/batched/Test_Batched_TeamGemm.hpp
  unit_test/batched/Test_Batched_TeamGemm_Real.hpp
  unit_test/batched/Test_Batched_TeamVectorGemm.hpp
  unit_test/batched/Test_Batched_TeamVectorGemm_Real.hpp
Labels: Cleanup

#947 Fix serial spmv for beta -1. Add test to catch bug
  src/sparse/impl/KokkosSparse_spmv_impl.hpp
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: bug
