Repository kokkos/kokkos-kernels, pull requests merged in 2021-09, with the labels that each got.

#1093 perf_test/blas/blas3: Disable simd verify for cuda/10.2.2
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
Labels: CompilerIssue

#1096 Fix #1089 (failing batched UTV tests)
  unit_test/batched/Test_Batched_TeamVectorSolveUTV.hpp
  unit_test/batched/Test_Batched_TeamVectorSolveUTV2.hpp
  unit_test/batched/Test_Batched_TeamVectorUTV.hpp
Labels: bug

#1091 Blas GEMM: fix early exit logic, see issue #1088
  src/blas/KokkosBlas3_gemm.hpp
  unit_test/blas/Test_Blas3_gemm.hpp
Labels: bug

#1100 Allow reading integer mtx files into floating-point matrices
  src/common/KokkosKernels_IOUtils.hpp
Labels: enhancement

#1102 Fix C's numCols in spadd simplified interface
  src/sparse/KokkosSparse_spadd.hpp
  unit_test/sparse/Test_Sparse_spadd.hpp
Labels: bug

#1107 Batched serial SVD
  src/batched/dense/KokkosBatched_SVD_Decl.hpp
  src/batched/dense/impl/KokkosBatched_SVD_Serial_Impl.hpp
  src/batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp
  test_common/KokkosKernels_TestUtils.hpp
  unit_test/batched/dense/Test_Batched_Dense.hpp
  unit_test/batched/dense/Test_Batched_SerialSVD.hpp
Labels: enhancement

#1112 Fix #1111: spmv tpl instantiations
  src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: bug

#1115 CrsMatrix: deprecate constructor without ncols input
  src/sparse/KokkosSparse_CrsMatrix.hpp
  unit_test/sparse/Test_Sparse_CrsMatrix.hpp
Labels: Cleanup

#1118 Fix SpGEMM for Nvidia Turing/Ampere
  src/common/KokkosKernels_HashmapAccumulator.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
Labels: bug

#1095 src/batched: Add BatchedDblBufGemm
  perf_test/blas/blas3/KokkosBlas3_common.hpp
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas3_perf_test.cpp
  src/batched/KokkosBatched_Util.hpp
  src/batched/dense/KokkosBatched_Gemm_Decl.hpp
  src/batched/dense/impl/KokkosBatched_Gemm_DblBuf_Impl.hpp
  src/batched/dense/impl/KokkosBatched_Gemm_Serial_Impl.hpp
  unit_test/batched/dense/Test_Batched_BatchedGemm.hpp
Labels: feature request, AT: STALE
