Repository kokkos/kokkos-kernels, pull requests merged in 2021-11, with the labels that each got.

#1153 Tpl rocblas and rocsparse
  cmake/Dependencies.cmake
  cmake/KokkosKernels_config.h.in
  cmake/Modules/FindTPLROCBLAS.cmake
  cmake/Modules/FindTPLROCSPARSE.cmake
  cmake/kokkoskernels_tpls.cmake
  src/CMakeLists.txt
  src/common/KokkosKernels_SparseUtils_rocsparse.hpp
  src/impl/tpls/KokkosBlas_Rocm_tpl.cpp
  src/impl/tpls/KokkosBlas_Rocm_tpl.hpp
  src/impl/tpls/KokkosBlas_tpl_spec.hpp
  src/impl/tpls/KokkosKernels_tpl_handles_decl.hpp
  src/impl/tpls/KokkosKernels_tpl_handles_def.hpp
  unit_test/blas/Test_Blas.hpp
  unit_test/blas/Test_Blas_rocblas.hpp
  unit_test/sparse/Test_Sparse.hpp
  unit_test/sparse/Test_Sparse_rocsparse.hpp
Labels: enhancement, feature request

#1151 SpMV: mismatch in #ifdef check and kernel specialization
  src/sparse/KokkosSparse_spmv.hpp
Labels: bug

#1159 Small fixes to spgemm, and plug gaps in testing
  src/common/KokkosKernels_IOUtils.hpp
  src/sparse/KokkosSparse_spgemm.hpp
  src/sparse/KokkosSparse_spgemm_handle.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp
  src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp
  unit_test/sparse/Test_Sparse_spgemm.hpp
Labels: bug

#1171 using namespace should be scoped to prevent name clashes, see issue #1170
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas_trtri_perf_test.hpp
  src/blas/impl/KokkosBlas3_trmm_impl.hpp
  src/blas/impl/KokkosBlas3_trsm_impl.hpp
  src/blas/impl/KokkosBlas_trtri_impl.hpp
Labels: bug

#1090 Experimental tensor-core SpMV for BsrMatrix
  src/CMakeLists.txt
  src/common/KokkosKernels_MemSpaceUtils.hpp
  src/impl/generated_specializations_cpp/spmv/KokkosSparse_spmv_bsrmatrix_eti_spec_inst.cpp.in
  src/impl/generated_specializations_hpp/KokkosSparse_spmv_bsrmatrix_eti_spec_avail.hpp.in
  src/impl/generated_specializations_hpp/KokkosSparse_spmv_bsrmatrix_eti_spec_decl.hpp.in
  src/sparse/KokkosSparse_BlockCrsMatrix.hpp
  src/sparse/KokkosSparse_CrsMatrix.hpp
  src/sparse/KokkosSparse_spmv.hpp
  src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
  src/sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: feature request

#1179 SpMV: fix catch all case to avoid compiler warnings
  src/sparse/KokkosSparse_spmv.hpp
Labels: bug

#1162 Use KOKKOS_IMPL_DO_NOT_USE_PRINTF instead of printf in kernels
  unit_test/sparse/Test_Sparse_findRelOffset.hpp
  unit_test/sparse/Test_Sparse_trsv.hpp
Labels: bug

#1182 Fix #threads setting in pcg for OpenMP
  perf_test/sparse/KokkosSparse_pcg.cpp
Labels: bug

#1185 Fixing a couple of small issue with tensor core spmv
  src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: Cleanup

#1189 Fix assert in src/sparse/KokkosSparse_BsrMatrix.hpp
  src/sparse/KokkosSparse_BsrMatrix.hpp
Labels: bug

#1188 Check that ordinal types are signed
  src/common/KokkosKernels_Handle.hpp
  src/sparse/KokkosSparse_BlockCrsMatrix.hpp
  src/sparse/KokkosSparse_BsrMatrix.hpp
  src/sparse/KokkosSparse_CrsMatrix.hpp
Labels: enhancement

#1199 Allow choosing coloring algorithm in multicolor GS
  src/common/KokkosKernels_Handle.hpp
  src/common/KokkosKernels_IOUtils.hpp
  src/common/KokkosKernels_Sorting.hpp
  src/sparse/KokkosSparse_gauss_seidel_handle.hpp
  src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Labels: enhancement

#1201 Add rocBLAS GEMV wrapper
  perf_test/blas/blas2/KokkosBlas2_gemv_perf_test.cpp
  src/blas/KokkosBlas2_gemv.hpp
  src/impl/tpls/KokkosBlas2_gemv_tpl_spec_avail.hpp
  src/impl/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp
  unit_test/blas/Test_Blas2_gemv.hpp
Labels: enhancement, performance

#1197 example/gmres: Use fabs
  example/gmres/gmres.hpp
  example/gmres/test_cmplx_A.cpp
  src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
Labels: bug, bug develop-only
