Repository kokkos/kokkos-kernels, pull requests merged in 2022-05, with the labels that each got.

#1396 Bspgemm fixes
  src/common/KokkosKernels_BlockUtils.hpp
  src/common/KokkosKernels_Sorting.hpp
  unit_test/sparse/Test_Sparse_bspgemm.hpp
Labels: Cleanup

#1398 Clean-up src: re-organizing the src directory
  src/CMakeLists.txt
  src/cmake/kokkoskernels_eti.cmake
  src/common/KokkosKernels_Half.hpp
  src/common/Kokkos_ArithTraits.hpp
  src/common/Kokkos_InnerProductSpaceTraits.hpp
Labels: Cleanup

#1401 Add ETI for D1 coloring
  src/CMakeLists.txt
  src/graph/KokkosGraph_Distance1Color.hpp
  src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
  src/graph/impl/KokkosGraph_color_d1_spec.hpp
  src/impl/generated_specializations_cpp/color_d1/KokkosGraph_color_d1_eti_spec_inst.cpp.in
  src/impl/generated_specializations_hpp/KokkosGraph_color_d1_eti_spec_avail.hpp.in
  src/impl/generated_specializations_hpp/KokkosGraph_color_d1_eti_spec_decl.hpp.in
Labels: enhancement, AT: PRE-TEST INSPECTED

#1403 D1 coloring: remove unused but set variable
  src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
Labels: Cleanup, AT: PRE-TEST INSPECTED

#1408 Fix colliding include guards (copy-paste mistake)
  src/impl/generated_specializations_hpp/KokkosGraph_color_d1_eti_spec_avail.hpp.in
  src/impl/generated_specializations_hpp/KokkosGraph_color_d1_eti_spec_decl.hpp.in
Labels: bug, AT: PRE-TEST INSPECTED

#1412 SpMV: fixing issues with unit-tests tolerance
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: Cleanup

#1368 Restructure docs
  docs/conf.py
  docs/developer/apidocs.rst
  docs/developer/apidocs/batched_dense.rst
  docs/developer/apidocs/batched_sparse.rst
  docs/developer/apidocs/blas1.rst
  docs/developer/apidocs/blas2.rst
  docs/developer/apidocs/blas3.rst
  docs/developer/apidocs/sparse.rst
  docs/developer/build_doc.rst
  docs/developer/contrib.rst
  docs/developer/index.rst
  docs/developer/style.rst
  docs/developer/write_developer_doc.rst
  docs/developer/write_user_doc.rst
  docs/index.rst
Labels: AT: WIP
