Repository kokkos/kokkos-kernels, pull requests merged in 2022-02, with the labels that each got.

#1295 KokkosKernels: adding variable that returns version as a single number
  CMakeLists.txt
  cmake/KokkosKernels_config.h.in
Labels: enhancement, feature request, BlocksPromotion

#1304 Fix 1303: maintain correct #cols on A in twostage
  src/sparse/impl/KokkosSparse_twostage_gauss_seidel_impl.hpp
Labels: bug, BlocksPromotion

#1302 Revert "Kokkos synch up: remove macro usage"
  src/batched/dense/impl/KokkosBatched_Axpy_Impl.hpp
  src/batched/sparse/KokkosBatched_JacobiPrec.hpp
  src/batched/sparse/impl/KokkosBatched_Spmv_Serial_Impl.hpp
  src/batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp
  src/batched/sparse/impl/KokkosBatched_Spmv_Team_Impl.hpp
  unit_test/common/Test_Common_ArithTraits.hpp
Labels: BlocksPromotion, AT: PRE-TEST INSPECTED

#1300 example/gmres: Switch scalar to bhalf_t
  example/gmres/gmres.hpp
  example/gmres/test_real_A.cpp
Labels: feature request

#1299 src/batched/dense: Add Gemm_DblBuf LayoutLeft operator
  src/batched/dense/impl/KokkosBatched_Gemm_DblBuf_Impl.hpp
Labels: enhancement, AT: PRE-TEST INSPECTED

#1282 Cleanup Kokkos header includes
  perf_test/sparse/KokkosSparse_pcg.hpp
  src/batched/dense/KokkosBatched_Test_BlockCrs_Util.hpp
  src/batched/sparse/KokkosBatched_Krylov_Handle.hpp
  src/common/KokkosKernels_ExecSpaceUtils.hpp
  src/common/KokkosKernels_PrintUtils.hpp
  src/common/KokkosKernels_SimpleUtils.hpp
  src/common/KokkosKernels_SparseUtils.hpp
  src/common/KokkosKernels_Utils.hpp
  src/common/KokkosKernels_VectorUtils.hpp
  src/graph/KokkosGraph_Distance1ColorHandle.hpp
  src/graph/KokkosGraph_Distance2ColorHandle.hpp
  src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
  src/graph/impl/KokkosGraph_Distance2Color_impl.hpp
  src/sparse/KokkosSparse_gauss_seidel_handle.hpp
  src/sparse/KokkosSparse_spadd_handle.hpp
  src/sparse/KokkosSparse_spgemm_handle.hpp
  src/sparse/KokkosSparse_spiluk_handle.hpp
  src/sparse/KokkosSparse_sptrsv_handle.hpp
  src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  src/sparse/impl/KokkosSparse_partitioning_impl.hpp
  test_common/KokkosBatched_Test_BlockCrs.hpp
Labels: Cleanup

#1312 Replace std::abs with ArithTraits::abs
  perf_test/batched/do-not-use/KokkosBatched_Test_Gemm_Cuda.cpp
  perf_test/batched/do-not-use/KokkosBatched_Test_Gemv_Host.hpp
  perf_test/batched/do-not-use/KokkosBatched_Test_LU_Cuda.cpp
  perf_test/batched/do-not-use/KokkosBatched_Test_Trsm_Cuda.cpp
  perf_test/batched/do-not-use/KokkosBatched_Test_Trsm_Host.hpp
  perf_test/sparse/KokkosSparse_spmv_blockcrs.cpp
  perf_test/sparse/KokkosSparse_spmv_bsr.cpp
  src/batched/KokkosBatched_Util.hpp
  src/batched/dense/KokkosBatched_Test_BlockCrs_Util.hpp
  src/batched/sparse/impl/KokkosBatched_GMRES_TeamVector_Impl.hpp
  src/batched/sparse/impl/KokkosBatched_GMRES_Team_Impl.hpp
  test_common/KokkosBatched_Test_BlockCrs.hpp
Labels: Cleanup

#1315 Fix bug in `spmv_mv_bsrmatrix()` for Ampere GPU arch
  src/sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
Labels: bug

#866 Update cmake minimum version to 3.16
  CMakeLists.txt
  cmake/kokkoskernels_tpls.cmake
  example/cmake/in-tree/CMakeLists.txt
  example/cmake/install/CMakeLists.txt
  install_test/CMakeLists.txt.in
Labels: BlocksPromotion

#1283 Remove unused memory space utility
  src/common/KokkosKernels_MemSpaceUtils.hpp
  src/sparse/KokkosSparse_spmv.hpp
Labels: Cleanup

#1320 Kokkos::Impl: removing a few more instances of throw_runtime_exception
  src/batched/dense/KokkosBatched_Kernel_Handle.hpp
  src/batched/dense/impl/KokkosBatched_Gemm_Armpl_Impl.hpp
  test_common/KokkosKernels_Test_Structured_Matrix.hpp
Labels: Cleanup

#1324 Fix matrix market reader for bfloat16.
  src/common/KokkosKernels_IOUtils.hpp
Labels: AT: PRE-TEST INSPECTED

#1322 Fix issue 1314
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: AT: PRE-TEST INSPECTED

#1325 Guard __device__ functions in KOKKOS_INLINE_FUNCTION for tensor core SpMV
  src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
Labels: AT: PRE-TEST INSPECTED

#1339 Fix nightly builds following promotion of the math functions in Kokkos
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
  src/batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp
  unit_test/batched/dense/Test_Batched_SerialSVD.hpp
Labels: Cleanup

#1340 Reduce lots of macro duplication in sparse unit tests
  unit_test/common/Test_Common_Test_All_Type_Combos.hpp
  unit_test/sparse/Test_Sparse_BlockCrsMatrix.hpp
  unit_test/sparse/Test_Sparse_BsrMatrix.hpp
  unit_test/sparse/Test_Sparse_CrsMatrix.hpp
  unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
  unit_test/sparse/Test_Sparse_gauss_seidel.hpp
  unit_test/sparse/Test_Sparse_replaceSumInto.hpp
  unit_test/sparse/Test_Sparse_replaceSumIntoLonger.hpp
  unit_test/sparse/Test_Sparse_spadd.hpp
  unit_test/sparse/Test_Sparse_spgemm.hpp
  unit_test/sparse/Test_Sparse_spgemm_jacobi.hpp
  unit_test/sparse/Test_Sparse_spiluk.hpp
  unit_test/sparse/Test_Sparse_spmv.hpp
  unit_test/sparse/Test_Sparse_spmv_blockcrs.hpp
  unit_test/sparse/Test_Sparse_spmv_bsr.hpp
  unit_test/sparse/Test_Sparse_sptrsv.hpp
  unit_test/sparse/Test_Sparse_trsv.hpp
Labels: Cleanup
