Repository kokkos/kokkos-kernels, pull requests merged in 2022-10, with the labels that each got.

#1531 Change template type for StaticCrsGraph in BsrMatrix
  sparse/src/KokkosSparse_BsrMatrix.hpp
Labels: CompatibilityUpdate

#1549 cm_test_all_sandia: updates and cleanup
  scripts/cm_test_all_sandia
Labels: AT: PRE-TEST INSPECTED

#1559 .github: Set minimum permissions
  .github/workflows/format.yml
  .github/workflows/osx.yml
Labels: AT: STALE

#1568 KokkosKernels: Remove listing of undefined TPL deps (trilinos/Trilinos#11152)
  cmake/Dependencies.cmake
Labels: patch-release-cherry-pick

#1566 Rotg update: fixing the interface
  blas/CMakeLists.txt
  blas/impl/KokkosBlas1_rotg_impl.hpp
  blas/impl/KokkosBlas1_rotg_spec.hpp
  blas/src/KokkosBlas1_rotg.hpp
  blas/tpls/KokkosBlas1_rotg_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_rotg_tpl_spec_decl.hpp
  blas/unit_test/Test_Blas1_rotg.hpp
Labels: enhancement, Cleanup

#1560 ROTMG: adding rotmg implementation to KokkosBlas
  blas/CMakeLists.txt
  blas/eti/generated_specializations_cpp/rotmg/KokkosBlas1_rotmg_eti_spec_inst.cpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_rotmg_eti_spec_avail.hpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_rotmg_eti_spec_decl.hpp.in
  blas/impl/KokkosBlas1_rotmg_impl.hpp
  blas/impl/KokkosBlas1_rotmg_spec.hpp
  blas/src/KokkosBlas1_rotmg.hpp
  blas/tpls/KokkosBlas1_rotmg_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_rotmg_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
  blas/unit_test/Test_Blas.hpp
  blas/unit_test/Test_Blas1_rotmg.hpp
  cmake/kokkoskernels_eti_floats.cmake
Labels: enhancement, feature request

#1578 Rotg fixes for issue #1577
  blas/tpls/KokkosBlas1_rotg_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_rotg_tpl_spec_decl.hpp
Labels: bug, Cleanup
