Repository kokkos/kokkos-kernels, pull requests merged in 2022-07, with the labels that each got.

#1453 dot perf test: adding support for HIP and SYCL backend
  perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test.cpp
  perf_test/blas/blas1/KokkosBlas_dot_perf_test.cpp
Labels: enhancement, AT: STALE

#1439 Sparse utils namespace
  perf_test/graph/KokkosGraph_mis_d2.cpp
  perf_test/sparse/KokkosSparse_block_pcg.cpp
  perf_test/sparse/KokkosSparse_sptrsv_supernode.cpp
  src/graph/KokkosGraph_Distance2Color.hpp
  src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp
  src/sparse/KokkosSparse_Utils.hpp
  src/sparse/KokkosSparse_gauss_seidel.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_spec.hpp
  unit_test/graph/Test_Graph_graph_color.hpp
  unit_test/graph/Test_Graph_graph_color_distance2.hpp
  unit_test/sparse/Test_Sparse_Transpose.hpp
  unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
  unit_test/sparse/Test_Sparse_spgemm.hpp
Labels: Cleanup

#1463 trsv: remove assumptions about entry order within rows
  src/sparse/impl/KokkosSparse_trsv_impl.hpp
  test_common/KokkosKernels_TestUtils.hpp
  unit_test/sparse/Test_Sparse_trsv.hpp
Labels: enhancement

#1468 Fix arithtraits warning
  src/common/Kokkos_ArithTraits.hpp
Labels: Cleanup

#1460 Blas serial axpy and nrm2
  src/blas/KokkosBlas1_axpby.hpp
  src/blas/KokkosBlas1_nrm2.hpp
  src/blas/impl/KokkosBlas_serial_axpy.hpp
  src/blas/impl/KokkosBlas_serial_nrm2.hpp
  unit_test/blas/Test_Blas.hpp
  unit_test/blas/Test_Blas_serial_axpy.hpp
  unit_test/blas/Test_Blas_serial_nrm2.hpp
Labels: feature request

#1476 Fixup drop layout template param in rank-0 views
  src/batched/dense/impl/KokkosBatched_Gemm_DblBuf_Impl.hpp
  src/blas/KokkosBlas_trtri.hpp
  src/blas/impl/KokkosBlas_trtri_spec.hpp
  src/impl/tpls/KokkosBlas_trtri_tpl_spec_avail.hpp
  src/impl/tpls/KokkosBlas_trtri_tpl_spec_decl.hpp
Labels: bug, Cleanup

#1472 BLAS: fixing test that access results before synching
  unit_test/blas/Test_Blas1_dot.hpp
  unit_test/blas/Test_Blas1_iamax.hpp
  unit_test/blas/Test_Blas1_nrm1.hpp
  unit_test/blas/Test_Blas1_nrm2.hpp
  unit_test/blas/Test_Blas1_nrm2_squared.hpp
  unit_test/blas/Test_Blas1_sum.hpp
Labels: bug

#1473 sycl: re-enabling test now that dpcpp has made progress
  unit_test/common/Test_Common.hpp
  unit_test/graph/Test_Graph_graph_color.hpp
Labels: Cleanup

#1477 Sparse: bsr transpose algorithm
  src/sparse/KokkosSparse_Utils.hpp
  unit_test/sparse/Test_Sparse_Transpose.hpp
Labels: feature request

#1479 Newton solver: serial on device implementation of Newton's method
  src/blas/impl/KokkosBlas_Newton_impl.hpp
  unit_test/blas/Test_Blas.hpp
  unit_test/blas/Test_Blas_Newton.hpp
Labels: feature request
