Repository kokkos/kokkos-kernels, pull requests merged in 2022-11, with the labels that each got.

#1580 ParILUT: convert two lambdas to functors
  sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp
Labels: CompilerIssue

#1582 First phase of SpGEMM TPL refactor
  sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp
  sparse/src/KokkosSparse_CrsMatrix.hpp
  sparse/src/KokkosSparse_spgemm_handle.hpp
Labels: enhancement, Cleanup

#1576 cm_generate_makefile: add rocblas, rocsparse tpl options
  cm_generate_makefile.bash
Labels: AT: STALE, AT: PRE-TEST INSPECTED

#1581 ROT: adding function to rotate two vector using Givens rotation coefficients
  blas/CMakeLists.txt
  blas/eti/generated_specializations_cpp/rot/KokkosBlas1_rot_eti_spec_inst.cpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_rot_eti_spec_avail.hpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_rot_eti_spec_decl.hpp.in
  blas/impl/KokkosBlas1_rot_impl.hpp
  blas/impl/KokkosBlas1_rot_spec.hpp
  blas/src/KokkosBlas1_rot.hpp
  blas/tpls/KokkosBlas1_rot_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_rot_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_rotg_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_rotmg_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
  blas/unit_test/Test_Blas.hpp
  blas/unit_test/Test_Blas1_rot.hpp
  blas/unit_test/Test_Blas1_rotmg.hpp
Labels: feature request

#1583 ROTM: adding blas 1 function for modified rotation
  blas/CMakeLists.txt
  blas/eti/generated_specializations_cpp/rotm/KokkosBlas1_rotm_eti_spec_inst.cpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_rotm_eti_spec_avail.hpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_rotm_eti_spec_decl.hpp.in
  blas/impl/KokkosBlas1_rotm_impl.hpp
  blas/impl/KokkosBlas1_rotm_spec.hpp
  blas/src/KokkosBlas1_rotm.hpp
  blas/tpls/KokkosBlas1_rotm_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_rotm_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
  blas/unit_test/Test_Blas.hpp
  blas/unit_test/Test_Blas1_rotm.hpp
Labels: enhancement, feature request

#1587 SPMM: fixing cuSPARSE issue with incompatible compute type and op
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
Labels: bug

#1591 Fix Trilinos issue #11033
  sparse/src/KokkosSparse_Utils_mkl.hpp
Labels: patch-release-cherry-pick

#1446 Add csr2csc
  docs/developer/apidocs/sparse.rst
  scripts/cm_test_all_sandia
  sparse/impl/KokkosSparse_spgemm_imp_outer.hpp
  sparse/impl/KokkosSparse_spmv_spec.hpp
  sparse/impl/KokkosSparse_spmv_struct_spec.hpp
  sparse/src/KokkosSparse_CcsMatrix.hpp
  sparse/src/KokkosSparse_CrsMatrix.hpp
  sparse/src/KokkosSparse_Utils.hpp
  sparse/src/KokkosSparse_ccs2crs.hpp
  sparse/src/KokkosSparse_crs2ccs.hpp
  sparse/src/KokkosSparse_csc2csr.hpp
  sparse/unit_test/Test_Sparse.hpp
  sparse/unit_test/Test_Sparse_TestUtils_RandCsMat.hpp
  sparse/unit_test/Test_Sparse_block_gauss_seidel.hpp
  sparse/unit_test/Test_Sparse_ccs2crs.hpp
  sparse/unit_test/Test_Sparse_crs2ccs.hpp
  sparse/unit_test/Test_Sparse_csc2csr.hpp
  test_common/KokkosKernels_MatrixConverter.cpp
  test_common/KokkosKernels_TestUtils.hpp
Labels: feature request

#1594 ROT* HIP: testing and improving rocBLAS support for ROT* kernels
  blas/tpls/KokkosBlas1_rot_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_rotg_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_rotm_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_rotmg_tpl_spec_decl.hpp
Labels: bug

#1598 VBD/VBDBIT D1 coloring: support distributed graphs
  graph/impl/KokkosGraph_Distance1Color_impl.hpp
  perf_test/graph/KokkosGraph_color.cpp
Labels: bug, enhancement

#1603 ROTMG: rocblas TPL turned off
  blas/tpls/KokkosBlas1_rotmg_tpl_spec_avail.hpp
Labels: bug

#1605 Disable compile-time check in cuda_data_type_from on supported scalar types for cuSPARSE
  sparse/src/KokkosSparse_Utils_cusparse.hpp
Labels: patch-release-cherry-pick

#1607 SPGEMM: fixing the rocsparse interface
  sparse/impl/KokkosSparse_spgemm_rocSPARSE_impl.hpp
Labels: bug
