Repository kokkos/kokkos-kernels, pull requests merged in 2022-06, with the labels that each got.

#1436 Common Utils: removing dependency on Sparse Utils in Common Utils
  src/common/KokkosKernels_Utils.hpp
  src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp
  src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  test_common/KokkosKernels_TestUtils.hpp
Labels: Cleanup

#1429 Minor changes for half precision paper
  perf_test/blas/blas3/KokkosBatched_BatchedGemm_benchmark.sh
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
  perf_test/blas/blas3/papers/kokkos-half-t-rse-escience-2022/reproducer.md
Labels: AT: STALE

#1447 Fix Trilinos issue #10612
  src/Kokkos_ArithTraits.hpp
Labels: bug

#1449 csc2csr: update Kokkos_Numeric.hpp header inclusion
  src/sparse/KokkosSparse_csc2csr.hpp
Labels: CompatibilityUpdate

#1451 Added https://kokkos-kernels.readthedocs.io
  README.md
  docs/index.rst
  docs/kokkos-promotion.txt
  docs/requirements.txt
Labels: Documentation
