Repository kokkos/kokkos-kernels, pull requests merged in 2022-01, with the labels that each got.

#1248 Update testing scripts
  scripts/cm_test_all_sandia
  scripts/update_lib.sh
Labels: AT: PRE-TEST INSPECTED

#1231 Fix compilation errors for multi-vectors in kk_print_1Dview()
  src/common/KokkosKernels_PrintUtils.hpp
  unit_test/common/Test_Common.hpp
  unit_test/common/Test_Common_IOUtils.hpp
Labels: bug

#1262 Work around hipcc size_t/int division with remainder bug
  test_common/KokkosKernels_Test_Structured_Matrix.hpp
Labels: CompilerIssue

#1261 src/batched: Use SerialOpt2 for 33 to 39 square matrices
  src/batched/dense/KokkosBatched_Gemm_Decl.hpp
Labels: enhancement

#1267 Examples: fixing some issues related to type checking
  perf_test/graph/KokkosGraph_mis_d2.cpp
  perf_test/sparse/CMakeLists.txt
Labels: bug, Cleanup

#1266 Avoid using `#ifdef KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*` macro guards
  src/Kokkos_InnerProductSpaceTraits.hpp
  src/batched/dense/impl/KokkosBatched_Eigendecomposition_Serial_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Eigendecomposition_TeamVector_Internal.hpp
  src/sparse/impl/KokkosSparse_spmv_struct_impl.hpp
Labels: Cleanup

#1254 .github/workflows: Add osx CI
  .github/workflows/format.yml
  .github/workflows/osx.yml
  perf_test/sparse/KokkosSparse_gs.cpp
  unit_test/blas/Test_Blas2_gemv.hpp
  unit_test/sparse/Test_Sparse_gauss_seidel.hpp
  unit_test/sparse/Test_Sparse_spadd.hpp
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: enhancement

#1265 Refactor `Algo::Level{2,3}::Blocked::mb()`
  src/batched/KokkosBatched_Util.hpp
  src/batched/dense/KokkosBatched_Vector_SIMD.hpp
  src/batched/dense/impl/KokkosBatched_Gemm_Serial_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Gemm_Team_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Gemv_Serial_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Gemv_Team_Internal.hpp
  src/batched/dense/impl/KokkosBatched_LU_Serial_Internal.hpp
  src/batched/dense/impl/KokkosBatched_LU_Team_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Trsm_Serial_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Trsm_Team_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Trsv_Serial_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Trsv_Team_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Vector_SIMD_Arith.hpp
  src/batched/dense/impl/KokkosBatched_Vector_SIMD_Math.hpp
Labels: Cleanup

#1281 Remove private Kokkos header include (`Cuda/Kokkos_Cuda_Half.hpp`)
  unit_test/sparse/Test_Sparse_spmv.hpp
Labels: bug

#1251 unit_test/batched: Add Batched GEMM bhalf tests
  src/KokkosKernels_Half.hpp
  src/Kokkos_ArithTraits.hpp
  test_common/KokkosKernels_TestUtils.hpp
  unit_test/batched/dense/Test_Batched_BatchedGemm.hpp
  unit_test/batched/dense/Test_Batched_BatchedGemm_Real.hpp
  unit_test/batched/dense/Test_Batched_SerialGemm.hpp
  unit_test/batched/dense/Test_Batched_SerialGemm_Real.hpp
  unit_test/batched/dense/Test_Batched_TeamGemm.hpp
  unit_test/batched/dense/Test_Batched_TeamGemm_Real.hpp
  unit_test/batched/dense/Test_Batched_TeamVectorGemm.hpp
  unit_test/batched/dense/Test_Batched_TeamVectorGemm_Real.hpp
Labels: AT: STALE

#1278 Rename `KOKKOS_IF_{HOST,DEVICE} -> KOKKOS_IF_ON_{HOST,DEVICE}`
  src/batched/KokkosBatched_Util.hpp
  src/batched/dense/impl/KokkosBatched_Eigendecomposition_Serial_Internal.hpp
  src/batched/dense/impl/KokkosBatched_Eigendecomposition_TeamVector_Internal.hpp
  src/sparse/impl/KokkosSparse_spmv_struct_impl.hpp
Labels: Cleanup
