Repository kokkos/kokkos-kernels, pull requests merged in 2022-09, with the labels that each got.

#1510 KokkosGraph_CoarsenHeuristics: remove volatile qualifier from join
  src/graph/KokkosGraph_CoarsenHeuristics.hpp
Labels: CompatibilityUpdate

#1508 cm_test_all_sandia: update modules for sogpu
  scripts/cm_test_all_sandia
Labels: AT: WIP

#1490 docs: Fix RTD build
  docs/CMakeLists.txt
  docs/Doxyfile.in
  docs/conf.py
Labels: AT: STALE

#1494 utils: implicit copy-assign deprecated in array_sum_reduce
  src/common/KokkosKernels_Utils.hpp
Labels: AT: STALE

#1517 Graph coarsen: fix test by adding pre-processor guards, issue #1516
  src/graph/KokkosGraph_CoarsenConstruct.hpp
  unit_test/graph/Test_Graph.hpp
Labels: bug, Cleanup

#1520 src/batched/dense: Barrier after broadcast
  src/KokkosKernels_Macros.hpp
  src/batched/dense/KokkosBatched_Vector_SIMD.hpp
Labels: bug

#1528 MIS2 aggregation: fix bug with uninitialized memory
  src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp
Labels: bug

#1529 Rotg: implementation of BLAS level1 rotg
  blas/CMakeLists.txt
  blas/eti/generated_specializations_cpp/rotg/KokkosBlas1_rotg_eti_spec_inst.cpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_rotg_eti_spec_avail.hpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_rotg_eti_spec_decl.hpp.in
  blas/impl/KokkosBlas1_rotg_impl.hpp
  blas/impl/KokkosBlas1_rotg_spec.hpp
  blas/src/KokkosBlas1_rotg.hpp
  blas/tpls/KokkosBlas1_rotg_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_rotg_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
  blas/unit_test/Test_Blas.hpp
  blas/unit_test/Test_Blas1_rotg.hpp
Labels: enhancement, feature request

#1532 Warning fixes: Apple Clang complains about [-Werror,-Wunused-but-set-variable]
  graph/impl/KokkosGraph_Distance2Color_impl.hpp
  perf_test/sparse/KokkosSparse_spmv_struct.cpp
  perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp
Labels: Cleanup

#1535 Fix spgemm cusparse
  sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp
Labels: bug, Cleanup

#1552 Avoid the SIMD code branch if the batched size is not a multiple of the vector length
  batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp
Labels: bug

#1553 Use CRS matrix sort, instead of Kokkos::sort on each row
  sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
Labels: performance
