Repository kokkos/kokkos-kernels, pull requests merged in 2022-12, with the labels that each got.

#1608 Batched dense tests: splitting batched dense unit-tests
  batched/dense/unit_test/CMakeLists.txt
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_Dense_GEMM.hpp
  batched/dense/unit_test/backends/Test_Cuda_Batched_GEMM.cpp
  batched/dense/unit_test/backends/Test_HIP_Batched_GEMM.cpp
  batched/dense/unit_test/backends/Test_OpenMPTarget_Batched_GEMM.cpp
  batched/dense/unit_test/backends/Test_OpenMP_Batched_GEMM.cpp
  batched/dense/unit_test/backends/Test_SYCL_Batched_GEMM.cpp
  batched/dense/unit_test/backends/Test_Serial_Batched_GEMM.cpp
  batched/dense/unit_test/backends/Test_Threads_Batched_GEMM.cpp
Labels: Cleanup

#1614 Make sure to call `ExecutionSpace::concurrency()` from an object
  common/src/KokkosKernels_Uniform_Initialized_MemoryPool.hpp
  example/graph/KokkosKernels_Example_Distance2GraphColor.cpp
  example/hashmap_accumulator/KokkosKernels_Example_HashmapAccumulator.cpp
  graph/src/KokkosGraph_CoarsenConstruct.hpp
  graph/src/KokkosGraph_Triangle.hpp
  perf_test/graph/KokkosGraph_color_d2.cpp
  perf_test/sparse/KokkosSparse_spmv_test.hpp
  perf_test/sparse/spmv/Kokkos_SPMV.hpp
  perf_test/sparse/spmv/Kokkos_SPMV_Inspector.hpp
  sparse/impl/KokkosSparse_bspgemm_impl_kkmem.hpp
  sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp
  sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  sparse/impl/KokkosSparse_spgemm_impl.hpp
  sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp
  sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
  sparse/impl/KokkosSparse_spmv_impl.hpp
  sparse/impl/KokkosSparse_spmv_struct_impl.hpp
Labels: CompatibilityUpdate

#1616 Cleanup messages printed at configuration time
  CMakeLists.txt
Labels: Cleanup

#1612 SWAP: adding implementation of level 1 BLAS function
  blas/CMakeLists.txt
  blas/eti/generated_specializations_cpp/swap/KokkosBlas1_swap_eti_spec_inst.cpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_swap_eti_spec_avail.hpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas1_swap_eti_spec_decl.hpp.in
  blas/impl/KokkosBlas1_swap_impl.hpp
  blas/impl/KokkosBlas1_swap_spec.hpp
  blas/src/KokkosBlas1_swap.hpp
  blas/tpls/KokkosBlas1_swap_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_swap_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
  blas/unit_test/Test_Blas.hpp
  blas/unit_test/Test_Blas1_swap.hpp
  docs/developer/apidocs/blas1.rst
Labels: feature request

#1619 Remove "slow mem space" device ETI
  cmake/kokkoskernels_eti_devices.cmake
  graph/CMakeLists.txt
  graph/impl/KokkosGraph_color_d1_spec.hpp
  sparse/CMakeLists.txt
  sparse/impl/KokkosSparse_bspgemm_numeric_spec.hpp
  sparse/impl/KokkosSparse_gauss_seidel_spec.hpp
  sparse/impl/KokkosSparse_spgemm_jacobi_spec.hpp
  sparse/impl/KokkosSparse_spgemm_numeric_spec.hpp
  sparse/impl/KokkosSparse_spgemm_symbolic_spec.hpp
Labels: Cleanup
