Repository kokkos/kokkos-kernels, pull requests merged in 2023-10, with the labels that each got.

#1990 CMake: Adding logic to catch bad Kokkos version
  CMakeLists.txt
Labels: enhancement

#1981 Common: remove half and bhalf implementations
  common/src/KokkosKernels_Half.hpp
  common/src/Kokkos_ArithTraits.hpp
  common/unit_test/Test_Common_ArithTraits.hpp
  test_common/KokkosKernels_TestUtils.hpp
Labels: Cleanup

#2004 iostream clean-up in benchmarks
  perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test_benchmark.cpp
  perf_test/blas/blas1/KokkosBlas_dot_perf_test_benchmark.cpp
Labels: bug, Cleanup

#2007 bhalf_t fix for isnan function
  common/src/Kokkos_ArithTraits.hpp
Labels: bug

#1999 Experimental hip cleanup
  batched/dense/impl/KokkosBatched_HostLevel_Gemm_Impl.hpp
  batched/dense/src/KokkosBatched_Vector.hpp
  blas/impl/KokkosBlas3_gemm_impl.hpp
  blas/impl/KokkosBlas3_gemm_spec.hpp
  blas/src/KokkosBlas2_gemv.hpp
  blas/tpls/KokkosBlas2_gemv_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas3_gemm_tpl_spec_avail.hpp
  cmake/KokkosKernels_config.h.in
  cmake/kokkoskernels_eti_devices.cmake
  common/src/KokkosKernels_ExecSpaceUtils.hpp
  common/src/KokkosKernels_default_types.hpp
  perf_test/batched/dense/KokkosBatched_Test_BlockTridiagDirect.cpp
  perf_test/batched/dense/KokkosBatched_Test_BlockTridiagJacobi.cpp
  perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test.cpp
  perf_test/blas/blas1/KokkosBlas_dot_perf_test.cpp
  perf_test/blas/blas2/KokkosBlas2_gemv_perf_test.cpp
  perf_test/blas/blas2/KokkosBlas2_gemv_perf_test_benchmark.cpp
  perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test_benchmark.cpp
  perf_test/graph/KokkosGraph_color.cpp
  perf_test/graph/KokkosGraph_color_d2.cpp
  perf_test/graph/KokkosGraph_mis_d2.cpp
  perf_test/sparse/KokkosSparse_pcg.cpp
  sparse/impl/KokkosSparse_spmv_impl.hpp
  sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
  sparse/src/KokkosSparse_CrsMatrix.hpp
  sparse/src/KokkosSparse_spgemm_handle.hpp
  sparse/src/KokkosSparse_spmv.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp
  test_common/Test_HIP.hpp
Labels: Cleanup

#2008 Bspgemm cusparse hang
  sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_avail.hpp
  sparse/unit_test/Test_Sparse_bspgemm.hpp
  sparse/unit_test/Test_Sparse_spgemm.hpp
Labels: bug, Cleanup

#1895 Axpby: improvement on unification attempt logic and on the execution of a diversity of situations
  blas/impl/KokkosBlas1_axpby_impl.hpp
  blas/impl/KokkosBlas1_axpby_mv_impl.hpp
  blas/impl/KokkosBlas1_axpby_spec.hpp
  blas/impl/KokkosBlas1_axpby_unification_attempt_traits.hpp
  blas/src/KokkosBlas1_axpby.hpp
  blas/unit_test/Test_Blas.hpp
  blas/unit_test/Test_Blas1_axpby.hpp
  blas/unit_test/Test_Blas1_axpby_unification.hpp
  blas/unit_test/Test_Blas2_ger.hpp
  blas/unit_test/Test_Blas2_syr.hpp
  common/src/KokkosKernels_helpers.hpp
Labels: bug, enhancement

#2014 KokkosBlas1_axpby: include <iostream> for debug builds
  blas/src/KokkosBlas1_axpby.hpp
Labels: bug, bug develop-only

#2013 Syr2 fix
  blas/unit_test/Test_Blas2_syr2.hpp
Labels: bug

#2026 Sptrsv check cusparse
  sparse/src/KokkosSparse_sptrsv.hpp
  sparse/src/KokkosSparse_sptrsv_handle.hpp
Labels: BlocksPromotion
