Repository kokkos/kokkos-kernels, pull requests merged in 2023-02, with the labels that each got.

#1653 Drop pre Kokkos 3.6 workaround
  blas/impl/KokkosBlas_util.hpp
Labels: Cleanup

#1654 Hands off `Kokkos::Impl::clock_tic`
  batched/dense/unit_test/Test_Batched_SerialTrmm.hpp
  batched/dense/unit_test/Test_Batched_SerialTrtri.hpp
  blas/unit_test/Test_Blas3_gemm.hpp
  blas/unit_test/Test_Blas3_trmm.hpp
  blas/unit_test/Test_Blas3_trsm.hpp
  blas/unit_test/Test_Blas_trtri.hpp
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas_trtri_perf_test.hpp
Labels: Cleanup

#1624 Mdf alg upgrade
  perf_test/sparse/CMakeLists.txt
  perf_test/sparse/KokkosSparse_mdf.cpp
  sparse/impl/KokkosSparse_mdf_impl.hpp
  sparse/src/KokkosSparse_mdf.hpp
  sparse/src/KokkosSparse_mdf_handle.hpp
  sparse/unit_test/Test_Sparse_mdf.hpp
Labels: enhancement

#1679 Prefer `Kokkos::View::{R->r}ank`
  batched/dense/impl/KokkosBatched_Axpy_Impl.hpp
  batched/dense/impl/KokkosBatched_Dot_Internal.hpp
  batched/dense/impl/KokkosBatched_Gemv_TeamVector_Impl.hpp
  batched/dense/impl/KokkosBatched_Gemv_Team_Impl.hpp
  batched/dense/impl/KokkosBatched_Gesv_Impl.hpp
  batched/dense/impl/KokkosBatched_HadamardProduct_Impl.hpp
  batched/dense/impl/KokkosBatched_Xpay_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_Serial_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_Team_Impl.hpp
  blas/impl/KokkosBlas1_axpby_impl.hpp
  blas/impl/KokkosBlas1_axpby_mv_impl.hpp
  blas/impl/KokkosBlas1_axpby_spec.hpp
  blas/impl/KokkosBlas2_team_gemv_spec.hpp
  blas/src/KokkosBlas1_axpby.hpp
  blas/src/KokkosBlas1_nrm2.hpp
  blas/tpls/KokkosBlas1_axpby_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_axpby_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_dot_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_iamax_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_nrm1_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_nrm2_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_nrminf_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp
Labels: Cleanup

#1678 Spgemm non-reuse: unification layer and TPLs
  sparse/CMakeLists.txt
  sparse/eti/generated_specializations_cpp/spgemm_noreuse/KokkosSparse_spgemm_noreuse_eti_spec_inst.cpp.in
  sparse/eti/generated_specializations_hpp/KokkosSparse_spgemm_noreuse_eti_spec_avail.hpp.in
  sparse/eti/generated_specializations_hpp/KokkosSparse_spgemm_noreuse_eti_spec_decl.hpp.in
  sparse/impl/KokkosSparse_spgemm_noreuse_spec.hpp
  sparse/src/KokkosSparse_spgemm.hpp
  sparse/tpls/KokkosSparse_spgemm_noreuse_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spgemm_noreuse_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  sparse/unit_test/Test_Sparse_spgemm.hpp
Labels: enhancement

#1680 CMake: export version and subversion to config file
  CMakeLists.txt
  cmake/KokkosKernels_config.h.in
  common/unit_test/Test_Common.hpp
  common/unit_test/Test_Common_Version.hpp
Labels: enhancement, Cleanup

#1681 Add utility KokkosSparse::removeCrsMatrixZeros(A, tol)
  sparse/src/KokkosSparse_Utils.hpp
  sparse/unit_test/Test_Sparse.hpp
  sparse/unit_test/Test_Sparse_Utils.hpp
  sparse/unit_test/Test_Sparse_removeCrsMatrixZeros.hpp
  sparse/unit_test/Test_Sparse_spgemm.hpp
Labels: enhancement, feature request

#1661 Adds a better parilut test with gmres
  blas/src/KokkosBlas3_trsm.hpp
  common/src/KokkosKernels_Error.hpp
  sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp
  sparse/src/KokkosSparse_LUPrec.hpp
  sparse/src/KokkosSparse_MatrixPrec.hpp
  sparse/src/KokkosSparse_Preconditioner.hpp
  sparse/src/KokkosSparse_par_ilut.hpp
  sparse/unit_test/Test_Sparse_gmres.hpp
  sparse/unit_test/Test_Sparse_par_ilut.hpp
Labels: WIP

#1615 Gemm mixed scalars
  blas/src/KokkosBlas1_dot.hpp
  blas/src/KokkosBlas1_nrm1.hpp
  blas/src/KokkosBlas1_nrm2_squared.hpp
  blas/src/KokkosBlas1_nrm2w_squared.hpp
  blas/unit_test/Test_Blas1_axpby.hpp
  blas/unit_test/Test_Blas1_axpy.hpp
  blas/unit_test/Test_Blas1_dot.hpp
  blas/unit_test/Test_Blas1_iamax.hpp
  blas/unit_test/Test_Blas1_mult.hpp
  blas/unit_test/Test_Blas1_nrm1.hpp
  blas/unit_test/Test_Blas1_nrm2.hpp
  blas/unit_test/Test_Blas1_nrm2w.hpp
  blas/unit_test/Test_Blas1_nrm2w_squared.hpp
  blas/unit_test/Test_Blas1_nrminf.hpp
  blas/unit_test/Test_Blas1_reciprocal.hpp
  blas/unit_test/Test_Blas1_scal.hpp
  blas/unit_test/Test_Blas1_sum.hpp
  blas/unit_test/Test_Blas1_team_update.hpp
  blas/unit_test/Test_Blas1_update.hpp
  blas/unit_test/Test_Blas2_gemv.hpp
  blas/unit_test/Test_Blas2_gemv_util.hpp
  blas/unit_test/Test_Blas3_gemm.hpp
  sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp
  sparse/unit_test/Test_Sparse_spmv.hpp
  sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Labels: bug, BlocksPromotion

#1665 add basis skeleton for KokkosKernels::print_configuration
  common/src/KokkosKernels_PrintConfiguration.hpp
  common/unit_test/Test_Common.hpp
  common/unit_test/Test_Common_PrintConfiguration.hpp
Labels: feature request

#1687 Versions: fixing the CMake logic to export Kokkos Kernels version
  CMakeLists.txt
Labels: BlocksPromotion

#1694 Test mixed scalars: more fixes related to mixed scalar tests
  blas/unit_test/Test_Blas1_nrm2w.hpp
  blas/unit_test/Test_Blas1_nrm2w_squared.hpp
  blas/unit_test/Test_Blas1_reciprocal.hpp
  blas/unit_test/Test_Blas1_team_mult.hpp
  blas/unit_test/Test_Blas1_team_update.hpp
  blas/unit_test/Test_Blas2_gemv.hpp
Labels: Cleanup, AT: WIP

#1706 team mult: fix type issue in max_error calculation
  blas/unit_test/Test_Blas1_team_mult.hpp
Labels: bug

#1691 Introduce KOKKOSKERNELS_ALL_COMPONENTS_ENABLED variable
  CMakeLists.txt
  cmake/kokkoskernels_components.cmake
Labels: bug

#1707 Kokkos Kernels version: need to use upper case variables
  CMakeLists.txt
Labels: bug

#1709 4.0.0 compatibility
  batched/KokkosBatched_Util.hpp
Labels: enhancement, CompatibilityUpdate
