Repository kokkos/kokkos-kernels, pull requests merged in 2023-06, with the labels that each got.

#1843 docs: Add profiling for compile times
  docs/developer/index.rst
  docs/developer/profiling.rst
Labels: AT: WIP

#1857 batched/unit_test: Disable simd dcomplex4 test in for intel > 19.05 and <= 2021.
  batched/dense/unit_test/Test_Batched_VectorView.hpp
Labels: CompilerIssue

#1862 sparse/src: Work around gnu compiler bug
  sparse/src/KokkosSparse_BsrMatrix.hpp
Labels: CompilerIssue

#1864 Workaround for spiluk and sptrsv stream tests with OMP_NUM_THREADS of 1, 2, 3
  sparse/unit_test/Test_Sparse_spiluk.hpp
  sparse/unit_test/Test_Sparse_sptrsv.hpp
Labels: bug

#1850 batched/dense: Add gesv DynRankView runtime checks
  batched/dense/impl/KokkosBatched_Gemv_Team_Impl.hpp
Labels: BlocksPromotion

#1837 Implement BLAS2 syr() and her() functionalities under kokkos-kernels syr()
  blas/CMakeLists.txt
  blas/eti/generated_specializations_cpp/syr/KokkosBlas2_syr_eti_spec_inst.cpp.in
  blas/eti/generated_specializations_hpp/KokkosBlas2_syr_eti_spec_avail.hpp.in
  blas/impl/KokkosBlas2_syr_impl.hpp
  blas/impl/KokkosBlas2_syr_spec.hpp
  blas/src/KokkosBlas2_syr.hpp
  blas/tpls/KokkosBlas2_syr_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas2_syr_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas2_syr_tpl_spec_decl_blas.hpp
  blas/tpls/KokkosBlas2_syr_tpl_spec_decl_cublas.hpp
  blas/tpls/KokkosBlas2_syr_tpl_spec_decl_rocblas.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
  blas/unit_test/Test_Blas.hpp
  blas/unit_test/Test_Blas2_syr.hpp
  docs/developer/apidocs/blas2.rst
Labels: feature request

#1867 KokkosKernels: Don't list include for non-existant 'batched' build dir (trilinos/Trilinos#11966)
  batched/CMakeLists.txt
Labels: CompatibilityUpdate, TrilinosPatchMatch

#1870 Correcting 'syr test' bug causing compilation errors with Trilinos
  blas/unit_test/Test_Blas2_syr.hpp
Labels: bug

#1868 MKL: support indices properly
  blas/tpls/KokkosBlas2_serial_gemv_tpl_spec_decl.hpp
  perf_test/sparse/KokkosSparse_spadd.cpp
  sparse/tpls/KokkosSparse_spgemm_noreuse_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spgemm_noreuse_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: bug

#1876 docs: Add testing table
  docs/_static/table_theme.css
  docs/conf.py
  docs/developer/index.rst
  docs/developer/testing_table.rst
Labels: Documentation, AT: WIP

#1882 oneMKL spmv
  sparse/src/KokkosSparse_Utils_mkl.hpp
  sparse/src/KokkosSparse_spmv.hpp
  sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  sparse/unit_test/Test_Sparse.hpp
Labels: enhancement, feature request
