Repository kokkos/kokkos-kernels, pull requests merged in 2023-12, with the labels that each got.

#1949 Add TPL support for KokkosBlas::dot
  CheckHostBlasReturnComplex.cmake
  blas/src/KokkosBlas1_dot.hpp
  blas/tpls/KokkosBlas1_dot_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_dot_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
Labels: enhancement, AT: PRE-TEST INSPECTED

#2048 Lapack: fixing issue with Magma TPL in gesv, trtri, etc...
  blas/src/KokkosBlas1_swap.hpp
  blas/unit_test/Test_Blas1_swap.hpp
  lapack/src/KokkosLapack_gesv.hpp
  lapack/tpls/KokkosLapack_Cuda_tpl.hpp
  lapack/tpls/KokkosLapack_gesv_tpl_spec_avail.hpp
  lapack/tpls/KokkosLapack_gesv_tpl_spec_decl.hpp
  lapack/tpls/KokkosLapack_magma.hpp
  lapack/tpls/KokkosLapack_trtri_tpl_spec_decl.hpp
  lapack/unit_test/Test_Lapack_gesv.hpp
Labels: bug, Cleanup

#2055 Link std::filesystem for IntelLLVM in perf_test/sparse
  perf_test/sparse/CMakeLists.txt
Labels: Cleanup

#2074 Async matrix release for MKL >= 2023.2 in SpMV
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: performance

#2072 Deprecate `KOKKOSLINALG_OPT_LEVEL`
  BUILD.md
  CMakeLists.txt
  common/src/KokkosLinAlg_config.h
Labels: Cleanup

#2050 ROCm 6 deprecation fixes for rocsparse
  sparse/src/KokkosSparse_Utils_rocsparse.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: Cleanup, AT: STALE

#2073 Don't call `optimize_gemv` for one-shot MKL spmv
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: performance
