Repository kokkos/kokkos-kernels, pull requests merged in 2023-07, with the labels that each got.

#1892 Remove non-existant dir from CMake include paths
  ode/CMakeLists.txt
Labels: TrilinosPatchMatch

#1893 MDF: move most expensive kernels over to hierarchical parallelism
  sparse/impl/KokkosSparse_mdf_impl.hpp
  sparse/src/KokkosSparse_mdf.hpp
  sparse/unit_test/Test_Sparse_mdf.hpp
Labels: enhancement, performance

#1894 MDF: convert remaining count functor to hierarchical parallelism
  sparse/impl/KokkosSparse_mdf_impl.hpp
  sparse/src/KokkosSparse_mdf.hpp
Labels: enhancement

#1896 ODE: adding adaptivity test for RK methods
  ode/impl/KokkosODE_RungeKutta_impl.hpp
  ode/unit_test/Test_ODE_RK.hpp
Labels: bug, enhancement

#1908 ODE: changing layout of temp mem in RK algorithms
  ode/impl/KokkosODE_RungeKutta_impl.hpp
  ode/unit_test/Test_ODE_RK.hpp
  ode/unit_test/Test_ODE_RK_chem.hpp
  perf_test/ode/KokkosODE_RK.cpp
Labels: enhancement

#1914 BLAS: fix assignable check in gemv and gemm
  blas/src/KokkosBlas2_gemv.hpp
  blas/src/KokkosBlas3_gemm.hpp
Labels: bug

#1916 mdf: fix initial value in select pivot functor
  sparse/impl/KokkosSparse_mdf_impl.hpp
  sparse/src/KokkosSparse_mdf.hpp
Labels: bug

#1912 Add TPL oneMKL GEMV support
  blas/src/KokkosBlas2_gemv.hpp
  blas/tpls/KokkosBlas2_gemv_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp
Labels: enhancement, feature request

#1925 Bsr compatibility
  common/impl/KokkosKernels_ViewUtils.hpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_impl_v42.hpp
Labels: Cleanup

#1923 remove triplicate sanity checks in BsrMatrix
  sparse/src/KokkosSparse_BsrMatrix.hpp
Labels: Cleanup

#1920 remove Intel 2017 code (no longer supported)
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: Cleanup
