Repository kokkos/kokkos-kernels, pull requests merged in 2023-05, with the labels that each got.

#1799 New performance test for par_ilut, ginkgo::par_ilut, and spill
  perf_test/Benchmark_Context.hpp
  perf_test/sparse/CMakeLists.txt
  perf_test/sparse/KokkosSparse_par_ilut.cpp
  sparse/unit_test/Test_Sparse_par_ilut.hpp
Labels: WIP

#1817 KokkosKernels: Remove TriBITS Kokkos subpackages (trilinos/Trilinos#11545)
  cmake/Dependencies.cmake
Labels: CompatibilityUpdate, TrilinosPatchMatch

#1812 Blas2 and 3 on stream
  blas/impl/KokkosBlas3_gemm_dotbased_impl.hpp
  blas/impl/KokkosBlas3_gemm_impl.hpp
  blas/impl/KokkosBlas3_gemm_spec.hpp
  blas/impl/KokkosBlas3_trmm_spec.hpp
  blas/impl/KokkosBlas3_trsm_spec.hpp
  blas/src/KokkosBlas2_gemv.hpp
  blas/src/KokkosBlas3_gemm.hpp
  blas/src/KokkosBlas3_trmm.hpp
  blas/src/KokkosBlas3_trsm.hpp
  blas/tpls/KokkosBlas3_gemm_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas3_trmm_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas3_trmm_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas3_trsm_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas3_trsm_tpl_spec_decl.hpp
  docs/developer/apidocs/blas2.rst
  docs/developer/apidocs/blas3.rst
  sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_decl.hpp
Labels: enhancement, feature request

#1810 Fix name mismatch with rocblas tpl spec layer for scal
  blas/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp
Labels: bug develop-only

#1822 Ger: adding documentation stubs in apidocs
  docs/developer/apidocs/blas2.rst
Labels: Documentation, AT: WIP

#1827 Kokkos 4 compatibility: modifying the preprocessor logic
  batched/KokkosBatched_Util.hpp
  perf_test/sparse/CMakeLists.txt
  sparse/impl/KokkosSparse_coo2crs_impl.hpp
  sparse/src/KokkosSparse_coo2crs.hpp
  sparse/unit_test/Test_Sparse.hpp
Labels: CompatibilityUpdate

#1834 Remove dead code guarded by `#ifdef KOKKOSKERNELS_INST_MEMSPACE_CUDAHOSTPINNEDSPACE`
  perf_test/sparse/KokkosSparse_spgemm_jacobi.cpp
Labels: Cleanup

#1836 Drop outdated workarounds for backward compatibility with Kokkos
  cmake/kokkos_backends.cmake
  common/src/KokkosKernels_default_types.hpp
Labels: Cleanup

#1821 SpMV: adding benchmark for spmv
  perf_test/sparse/CMakeLists.txt
  perf_test/sparse/KokkosSparse_spmv_benchmark.cpp
Labels: enhancement

#1840 cm_test_all_sandia: update to add caraway queues for MI210, MI250
  cm_generate_makefile.bash
  scripts/cm_test_all_sandia
Labels: AT: WIP

#1835 Do not change memory spaces instantiation defaults based on Kokkos_ENABLE_CUDA_UVM
  CMakeLists.txt
  cmake/kokkoskernels_eti_devices.cmake
Labels: CompatibilityUpdate

#1849 Update cmake option naming in docs/comments
  BUILD.md
  cmake/kokkoskernels_eti_devices.cmake
Labels: AT: WIP

#1848 blas/tpls: Fix gemm include guard typo
  blas/tpls/KokkosBlas3_gemm_tpl_spec_avail.hpp
Labels: Cleanup
