Repository kokkos/kokkos-kernels, pull requests merged in 2023-11, with the labels that each got.

#2031 Adding Changelog for Release 4.2.0
  CHANGELOG.md
Labels: AT: WIP

#2038 Lapack: cusolver TPL logic and support for gesv
  CMakeLists.txt
  blas/tpls/KokkosBlas2_syr2_tpl_spec_decl_rocblas.hpp
  cm_generate_makefile.bash
  cmake/Dependencies.cmake
  cmake/KokkosKernels_config.h.in
  cmake/Modules/FindTPLCUSOLVER.cmake
  cmake/kokkoskernels_features.cmake
  cmake/kokkoskernels_tpls.cmake
  common/src/KokkosKernels_PrintConfiguration.hpp
  common/src/KokkosKernels_TplsVersion.hpp
  lapack/impl/KokkosLapack_gesv_spec.hpp
  lapack/tpls/KokkosLapack_Cuda_tpl.hpp
  lapack/tpls/KokkosLapack_cusolver.hpp
  lapack/tpls/KokkosLapack_gesv_tpl_spec_avail.hpp
  lapack/tpls/KokkosLapack_gesv_tpl_spec_decl.hpp
  lapack/unit_test/Test_Lapack_gesv.hpp
  scripts/cm_test_all_sandia
Labels: enhancement, feature request

#2043 Adding Changelog for Release 4.2.0 (#2031)
  CHANGELOG.md
Labels: AT: WIP

#2032 BLAS: nrm1 TPL refactor
  blas/tpls/KokkosBlas1_nrm1_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_nrm1_tpl_spec_decl.hpp
  blas/unit_test/Test_Blas1_nrm1.hpp
Labels: enhancement, Cleanup
