Repository kokkos/kokkos-kernels, pull requests merged in 2023-09, with the labels that each got.

#1957 SPMV_Struct_Functor: initialize numExterior to 0
  sparse/impl/KokkosSparse_spmv_struct_impl.hpp
Labels: AT: STALE

#1966 Fix sort_and_merge functions for in-place case
  sparse/src/KokkosSparse_SortCrs.hpp
  sparse/unit_test/Test_Sparse_SortCrs.hpp
Labels: bug

#1973 Fix #1972
  ode/unit_test/Test_ODE_Newton.hpp
  test_common/Test_Cuda.hpp
Labels: bug

#1968 MDF: set default verbosity explicitly to avoid valgrind warnings
  sparse/src/KokkosSparse_mdf_handle.hpp
Labels: Cleanup, AT: PRE-TEST INSPECTED

#1976 OrdinalTraits: constexpr functions
  sparse/src/KokkosSparse_OrdinalTraits.hpp
Labels: Cleanup

#1975 small typo
  README.md
Labels: Cleanup, AT: RETEST

#1977 KokkosKernels: switching from printf macro to function
  batched/dense/impl/KokkosBatched_Axpy_Impl.hpp
  batched/dense/impl/KokkosBatched_Copy_Impl.hpp
  batched/dense/impl/KokkosBatched_Dot_Internal.hpp
  batched/dense/impl/KokkosBatched_Gesv_Impl.hpp
  batched/dense/impl/KokkosBatched_HadamardProduct_Impl.hpp
  batched/dense/impl/KokkosBatched_Xpay_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_Serial_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_Team_Impl.hpp
  batched/sparse/src/KokkosBatched_JacobiPrec.hpp
  blas/src/KokkosBlas1_nrm2.hpp
  blas/unit_test/Test_Blas2_ger.hpp
  blas/unit_test/Test_Blas2_syr.hpp
  common/src/KokkosKernels_Error.hpp
  common/src/KokkosKernels_SimpleUtils.hpp
  common/unit_test/Test_Common_ArithTraits.hpp
  common/unit_test/Test_Common_LowerBound.hpp
  common/unit_test/Test_Common_UpperBound.hpp
  ode/impl/KokkosODE_Newton_impl.hpp
  sparse/src/KokkosSparse_spmv_team.hpp
  sparse/unit_test/Test_Sparse_spmv.hpp
Labels: Cleanup

#1950 Revise KokkosBlas::nrm2 TPL implementation
  blas/tpls/KokkosBlas1_nrm2_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_nrm2_tpl_spec_decl.hpp
Labels: enhancement

#1938 docs: Improve formatting
  batched/dense/src/KokkosBatched_HostLevel_Gemm.hpp
Labels: AT: WIP

#1979 Improve KokkosSparse_kk_spmv
  perf_test/sparse/KokkosSparse_kk_spmv.cpp
Labels: enhancement
