Repository kokkos/kokkos-kernels, pull requests merged in 2023-03, with the labels that each got.

#1704 blas/blas1: Fix a couple documentation typos.
  blas/src/KokkosBlas1_mult.hpp
  blas/src/KokkosBlas1_nrm2w.hpp
  blas/src/KokkosBlas1_reciprocal.hpp
Labels: AT: WIP

#1701 use rocsparse_spmv_ex for rocm >= 5.4.0
  sparse/src/KokkosSparse_Utils_rocsparse.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: CompatibilityUpdate

#1698 CUSPARSE_MM_ALG_DEFAULT deprecated by cuSparse 11.1
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
Labels: CompatibilityUpdate

#1714 print the patch that clang-format-8 wants to apply
  .github/workflows/format.yml
Labels: enhancement

#1726 .github: Automation reminder
  .github/workflows/format.yml
Labels: AT: WIP

#1723 Allow an HTML-only docs build
  .github/workflows/docs.yml
  docs/CMakeLists.txt
Labels: Documentation

#1757 Patch Trilinos #11663
  sparse/src/KokkosSparse_spgemm_symbolic.hpp
Labels: patch-release-cherry-pick, TrilinosPatchMatch

#1664 Spgemm perf test enhancements
  perf_test/KokkosKernels_perf_test_utilities.hpp
  perf_test/graph/KokkosGraph_color.cpp
  perf_test/graph/KokkosGraph_run_triangle.hpp
  perf_test/sparse/KokkosSparse_multimem_spgemm.hpp
  perf_test/sparse/KokkosSparse_run_spgemm.hpp
  perf_test/sparse/KokkosSparse_run_spgemm_jacobi.hpp
  perf_test/sparse/KokkosSparse_spgemm.cpp
  perf_test/sparse/KokkosSparse_spgemm_jacobi.cpp
  test_common/KokkosKernels_TestParameters.hpp
  test_common/KokkosKernels_TestUtils.hpp
Labels: enhancement

#1744 Add exec instance support to sort/sort_and_merge utils
  common/src/KokkosKernels_SimpleUtils.hpp
  sparse/src/KokkosSparse_SortCrs.hpp
  sparse/unit_test/Test_Sparse_SortCrs.hpp
Labels: enhancement

#1765 docs: Include BatchedGemm
  docs/developer/apidocs.rst
  docs/developer/apidocs/batched_dense_host.rst
Labels: AT: WIP

#1759 MDF: Minor changes to interface for ifpack2 impl
  .gitignore
  cm_generate_makefile.bash
  sparse/src/KokkosSparse_mdf.hpp
  sparse/src/KokkosSparse_mdf_handle.hpp
Labels: patch-release-cherry-pick, AT: PRE-TEST INSPECTED
