Repository kokkos/kokkos-kernels, pull requests merged in 2023-04, with the labels that each got.

#1763 Roc tpls upgrade
  cmake/Dependencies.cmake
  cmake/Modules/FindTPLROCBLAS.cmake
  cmake/Modules/FindTPLROCSPARSE.cmake
  sparse/unit_test/Test_Sparse_rocsparse.hpp
Labels: Cleanup

#1742 spgemm handle: check that A,B,C graphs never change
  common/src/KokkosKernels_SimpleUtils.hpp
  sparse/src/KokkosSparse_spgemm_handle.hpp
  sparse/src/KokkosSparse_spgemm_numeric.hpp
  sparse/src/KokkosSparse_spgemm_symbolic.hpp
  sparse/unit_test/Test_Sparse_spgemm.hpp
Labels: enhancement, feature request, AT: STALE

#1778 Batched Gesv: initializing variable to make compiler happy
  batched/dense/impl/KokkosBatched_Gesv_Impl.hpp
Labels: Cleanup

#1752 Re-enable and clean up triangle counting perf test
  graph/src/KokkosGraph_Triangle.hpp
  perf_test/KokkosKernels_perf_test_utilities.hpp
  perf_test/graph/CMakeLists.txt
  perf_test/graph/KokkosGraph_multimem_triangle.hpp
  perf_test/graph/KokkosGraph_run_triangle.hpp
  perf_test/graph/KokkosGraph_triangle.cpp
  sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp
  sparse/src/KokkosSparse_IOUtils.hpp
Labels: enhancement, Cleanup

#1773 Sort and merge improvements
  sparse/src/KokkosSparse_SortCrs.hpp
  sparse/unit_test/Test_Sparse_SortCrs.hpp
Labels: enhancement

#1785 Add --enable-docs option to cm_generate_makefile
  cm_generate_makefile.bash
Labels: enhancement

#1779 Refactor MKL TPL for both CPU and GPU usage
  cmake/Modules/FindTPLMKL.cmake
Labels: AT: PRE-TEST INSPECTED

#1796 scripts: Fix github-DOCS
  .github/workflows/docs.yml
Labels: AT: WIP

#1800 Fix #1798
  test_common/KokkosKernels_TestUtils.hpp
Labels: bug

#1803 Blas1 on stream
  blas/impl/KokkosBlas1_abs_impl.hpp
  blas/impl/KokkosBlas1_abs_spec.hpp
  blas/impl/KokkosBlas1_axpby_impl.hpp
  blas/impl/KokkosBlas1_axpby_mv_impl.hpp
  blas/impl/KokkosBlas1_axpby_spec.hpp
  blas/impl/KokkosBlas1_mult_impl.hpp
  blas/impl/KokkosBlas1_mult_spec.hpp
  blas/impl/KokkosBlas1_reciprocal_impl.hpp
  blas/impl/KokkosBlas1_reciprocal_spec.hpp
  blas/impl/KokkosBlas1_scal_impl.hpp
  blas/impl/KokkosBlas1_scal_mv_impl.hpp
  blas/impl/KokkosBlas1_scal_spec.hpp
  blas/impl/KokkosBlas1_update_impl.hpp
  blas/impl/KokkosBlas1_update_spec.hpp
  blas/src/KokkosBlas1_abs.hpp
  blas/src/KokkosBlas1_axpby.hpp
  blas/src/KokkosBlas1_fill.hpp
  blas/src/KokkosBlas1_mult.hpp
  blas/src/KokkosBlas1_reciprocal.hpp
  blas/src/KokkosBlas1_scal.hpp
  blas/src/KokkosBlas1_update.hpp
  blas/tpls/KokkosBlas1_abs_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_axpby_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_axpby_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_mult_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_reciprocal_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_scal_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_update_tpl_spec_avail.hpp
  perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test_benchmark.cpp
Labels: enhancement, feature request

#1805 Blas1: docs update for PR #1803
  blas/src/KokkosBlas1_abs.hpp
  blas/src/KokkosBlas1_axpby.hpp
  blas/src/KokkosBlas1_fill.hpp
  blas/src/KokkosBlas1_mult.hpp
  blas/src/KokkosBlas1_reciprocal.hpp
  blas/src/KokkosBlas1_scal.hpp
  blas/src/KokkosBlas1_update.hpp
  docs/developer/apidocs/blas1.rst
Labels: Documentation, AT: WIP

#1768 docs: Add stubs for some sparse APIs
  docs/developer/apidocs/sparse.rst
  docs/developer/build_doc.rst
  docs/developer/contrib.rst
  sparse/src/KokkosSparse_gauss_seidel.hpp
  sparse/src/KokkosSparse_gmres.hpp
  sparse/src/KokkosSparse_par_ilut.hpp
  sparse/src/KokkosSparse_spgemm.hpp
Labels: AT: WIP

#1795 Norms on stream
  blas/impl/KokkosBlas1_dot_impl.hpp
  blas/impl/KokkosBlas1_dot_mv_impl.hpp
  blas/impl/KokkosBlas1_dot_spec.hpp
  blas/impl/KokkosBlas1_iamax_impl.hpp
  blas/impl/KokkosBlas1_iamax_spec.hpp
  blas/impl/KokkosBlas1_nrm1_impl.hpp
  blas/impl/KokkosBlas1_nrm1_spec.hpp
  blas/impl/KokkosBlas1_nrm2_impl.hpp
  blas/impl/KokkosBlas1_nrm2_spec.hpp
  blas/impl/KokkosBlas1_nrm2w_impl.hpp
  blas/impl/KokkosBlas1_nrm2w_spec.hpp
  blas/impl/KokkosBlas1_nrminf_impl.hpp
  blas/impl/KokkosBlas1_nrminf_spec.hpp
  blas/impl/KokkosBlas1_sum_impl.hpp
  blas/impl/KokkosBlas1_sum_spec.hpp
  blas/src/KokkosBlas1_dot.hpp
  blas/src/KokkosBlas1_iamax.hpp
  blas/src/KokkosBlas1_nrm1.hpp
  blas/src/KokkosBlas1_nrm2.hpp
  blas/src/KokkosBlas1_nrm2_squared.hpp
  blas/src/KokkosBlas1_nrm2w.hpp
  blas/src/KokkosBlas1_nrm2w_squared.hpp
  blas/src/KokkosBlas1_nrminf.hpp
  blas/src/KokkosBlas1_sum.hpp
  blas/tpls/KokkosBlas1_dot_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_dot_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_iamax_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_iamax_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_nrm1_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_nrm1_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_nrm2_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_nrm2_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_nrm2w_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_nrminf_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_nrminf_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas1_sum_tpl_spec_avail.hpp
Labels: enhancement, feature request
