Repository kokkos/kokkos-kernels, pull requests merged in 2023-01, with the labels that each got.

#1579 Update kk_get_free_total_memory for SYCL
  common/src/KokkosKernels_ExecSpaceUtils.hpp
Labels: Cleanup, AT: PRE-TEST INSPECTED

#1628 Fix #1627: cusparse 11.0-11.3 spgemm symbolic wrapper
  sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_decl.hpp
  sparse/unit_test/Test_Sparse_spgemm.hpp
Labels: bug, enhancement, BlocksPromotion

#1635 KokkosKernels: Use KOKKOSKERNELS_INCLUDE_DIRECTORIES() (TriBITSPub/TriBITS#429)
  perf_test/CMakeLists.txt
Labels: BlocksPromotion, patch-release-cherry-pick, TrilinosPatchMatch

#1637 SWAP: fixing obvious mistake in TPL layer : (
  blas/tpls/KokkosBlas1_swap_tpl_spec_decl.hpp
Labels: bug, BlocksPromotion

#1638 ROTMG: loosen unit-test tolerance for Host TPLs
  blas/unit_test/Test_Blas1_rotmg.hpp
Labels: Cleanup, BlocksPromotion

#1645 CMake: update package COMPATIBILITY mode in anticipation of release 4.0
  cmake/kokkoskernels_tribits.cmake
Labels: BlocksPromotion

#1626 draft #5 Added google benchmark to kokkos kernel and to the CI
  .github/workflows/osx.yml
  perf_test/BenchmarkMain.cpp
  perf_test/Benchmark_Context.hpp
  perf_test/CMakeLists.txt
Labels: AT: PRE-TEST INSPECTED

#1641 Rename component options to avoid overloaded usage in Trilinos
  CMakeLists.txt
  batched/CMakeLists.txt
  batched/dense/unit_test/CMakeLists.txt
  batched/sparse/unit_test/CMakeLists.txt
  blas/CMakeLists.txt
  cmake/kokkoskernels_components.cmake
Labels: BlocksPromotion

#1632 Cuda/12 with CuSPARSE updates
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
  test_common/Test_Cuda.hpp
Labels: BlocksPromotion, patch-release-cherry-pick

#1659 Fix an error in Krylov Handle documentation
  batched/sparse/src/KokkosBatched_Krylov_Handle.hpp
Labels: AT: WIP
