Repository kokkos/kokkos-kernels, pull requests merged in 2023-08, with the labels that each got.

#1924 Newton solver
  CMakeLists.txt
  blas/impl/KokkosBlas_Newton_impl.hpp
  blas/unit_test/Test_Blas.hpp
  ode/impl/KokkosODE_Newton_impl.hpp
  ode/src/KokkosODE_Newton.hpp
  ode/src/KokkosODE_RungeKutta.hpp
  ode/src/KokkosODE_Types.hpp
  ode/unit_test/Test_ODE.hpp
  ode/unit_test/Test_ODE_Newton.hpp
Labels: feature request

#1926 Fix cm_generate_makefile --boundscheck
  cm_generate_makefile.bash
Labels: bug

#1941 .github/workflows/docs.yml: Use up-to-date doxygen version
  .github/workflows/docs.yml
Labels: AT: WIP

#1940 Avoid enum without fixed underlying type to fix SYCL
  ode/src/KokkosODE_Types.hpp
Labels: Cleanup

#1934 docs: Note which build has eti disabled
  docs/developer/testing_table.rst
Labels: AT: WIP

#1944 Unit-Test: adding specific test for block sparse functions
  sparse/unit_test/CMakeLists.txt
  sparse/unit_test/Test_BlockSparse.hpp
  sparse/unit_test/Test_Sparse.hpp
  sparse/unit_test/backends/Test_Cuda_BlockSparse.cpp
  sparse/unit_test/backends/Test_HIP_BlockSparse.cpp
  sparse/unit_test/backends/Test_OpenMPTarget_BlockSparse.cpp
  sparse/unit_test/backends/Test_OpenMP_BlockSparse.cpp
  sparse/unit_test/backends/Test_SYCL_BlockSparse.cpp
  sparse/unit_test/backends/Test_Serial_BlockSparse.cpp
  sparse/unit_test/backends/Test_Threads_BlockSparse.cpp
Labels: enhancement, Cleanup

#1945 Speed up BSR spmv tests
  sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Labels: enhancement

#1948 .github/workflows: Pin sphinx version
  .github/workflows/docs.yml
Labels: AT: WIP

#1932 Adding exec space instance to spmv
  docs/developer/apidocs/sparse.rst
  perf_test/sparse/KokkosSparse_spmv_merge.cpp
  perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_impl_v42.hpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
  sparse/impl/KokkosSparse_spmv_impl.hpp
  sparse/impl/KokkosSparse_spmv_spec.hpp
  sparse/impl/KokkosSparse_spmv_struct_impl.hpp
  sparse/impl/KokkosSparse_spmv_struct_spec.hpp
  sparse/src/KokkosSparse_BsrMatrix.hpp
  sparse/src/KokkosSparse_Utils_cusparse.hpp
  sparse/src/KokkosSparse_Utils_rocsparse.hpp
  sparse/src/KokkosSparse_spmv.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_struct_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
  sparse/unit_test/Test_Sparse_replaceSumIntoLonger.hpp
  sparse/unit_test/Test_Sparse_spmv.hpp
Labels: enhancement

#1958 Update create_gs_handle docs
  sparse/src/KokkosKernels_Handle.hpp
Labels: AT: WIP
