Repository kokkos/kokkos-kernels, pull requests merged in 2024-07, with the labels that each got.

#2272 BLAS - gemv: using fallback when mode is 't' or 'c' and onemkl is used
  blas/src/KokkosBlas2_gemv.hpp
Labels: bug

#2247 A little sptrsv cleanup before the main block effort
  sparse/impl/KokkosSparse_spiluk_numeric_impl.hpp
  sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
  sparse/impl/KokkosSparse_sptrsv_solve_spec.hpp
  sparse/src/KokkosKernels_Handle.hpp
  sparse/src/KokkosSparse_sptrsv_handle.hpp
Labels: AT: STALE

#2274 Sparse - SpMV: removing calls to unsuported oneapi - MKL functions
  sparse/src/KokkosSparse_spmv.hpp
Labels: bug

#2273 Support non-squared matrice in spmv_team
  sparse/impl/KokkosSparse_spmv_team_spec.hpp
  sparse/src/KokkosSparse_spmv_team.hpp
Labels: enhancement

#2243 .github/workflows: Auto trigger AT2 ci upon review
  .github/workflows/bdw.yml
  .github/workflows/h100.yml
  .github/workflows/mi210.yml
  .github/workflows/spr.yml
Labels: AT: WIP, AT2-SPECIAL-APPROVAL
