Repository kokkos/kokkos-kernels, pull requests merged in 2024-04, with the labels that each got.

#2164 Fix #2156
  sparse/src/KokkosSparse_spmv.hpp
  sparse/src/KokkosSparse_spmv_handle.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: bug, performance

#2168 Don't try to use space instance in classic MKL spmv
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: bug

#2169 CHANGELOG.md: 4.3.00 update to develop
  CHANGELOG.md
Labels: AT: WIP

#2174 Add AutoTester2 CI Configs (Sans Power9 & ROCM w/ TPLS)
  .github/workflows/bdw.yml
  .github/workflows/h100.yml
  .github/workflows/mi210.yml
  .github/workflows/spr.yml
  .github/workflows/volta70.yml
Labels: AT: WIP

#2182 At2 ROCM+TPL fixes, remove volta70 too
  .github/workflows/mi210.yml
  .github/workflows/volta70.yml
Labels: AT: WIP

#2186 workflows/osx.yml: test against most recent kokkos tag
  .github/workflows/osx.yml
Labels: AT: WIP

#2183 Resolve vortex compilation issue by resolving (potentially) duplicate symbol
  blas/tpls/KokkosBlas2_syr2_tpl_spec_decl_blas.hpp
  blas/tpls/KokkosBlas2_syr_tpl_spec_decl_blas.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
Labels: TrilinosPatchMatch
