Repository kokkos/kokkos-kernels, pull requests merged in 2024-08, with the labels that each got.

#2173 cmake: add CMake language support for CUDA/HIP
  CMakeLists.txt
  cmake/kokkoskernels_tribits.cmake
Labels: enhancement, feature request

#2296 SpAdd handle: delete sort_option getter/setter
  sparse/src/KokkosSparse_spadd_handle.hpp
Labels: bug

#2297 Some compilers throw shadow warnings in static functions
  sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
Labels: AT: PRE-TEST INSPECTED

#2294 Update changelog for 4.4.00
  CHANGELOG.md
Labels: AT: WIP

#2304 Release workflow
  .github/workflows/release.yml
Labels: enhancement, AT2-SPECIAL-APPROVAL

#2293 Improve crs/bsr sorting performance
  common/src/KokkosKernels_SimpleUtils.hpp
  common/src/KokkosKernels_Utils.hpp
  perf_test/sparse/CMakeLists.txt
  perf_test/sparse/KokkosSparse_sort_crs.cpp
  sparse/impl/KokkosSparse_sort_crs_impl.hpp
  sparse/src/KokkosSparse_SortCrs.hpp
  sparse/src/KokkosSparse_Utils.hpp
Labels: performance

#2302 Update version to 4.4.99
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/osx.yml
  CMakeLists.txt
Labels: AT2-SPECIAL-APPROVAL

#2306 Deprecate redundant team-level sort functions
  common/src/KokkosKernels_Sorting.hpp
  common/unit_test/Test_Common_Sorting.hpp
  graph/src/KokkosGraph_CoarsenConstruct.hpp
  sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  sparse/impl/KokkosSparse_mdf_impl.hpp
Labels: Cleanup

#2310 update changelog for 4.4.00
  CHANGELOG.md
Labels: AT: WIP

#2313 Restore size_t as default offset, in Tribits builds
  cmake/kokkoskernels_eti_offsets.cmake
Labels: TrilinosPatchMatch

#2314 Fix minor typing error.
  perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test_benchmark.cpp
  perf_test/blas/blas1/KokkosBlas_dot_perf_test.cpp
  perf_test/blas/blas1/KokkosBlas_dot_perf_test_benchmark.cpp
Labels: Cleanup

#2277 Implement batched serial pttrs
  batched/dense/impl/KokkosBatched_Pttrs_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Pttrs_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Pttrs.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_SerialPttrs.hpp
  batched/dense/unit_test/Test_Batched_SerialPttrs_Complex.hpp
  batched/dense/unit_test/Test_Batched_SerialPttrs_Real.hpp
  blas/impl/KokkosBlas_util.hpp
Labels: feature request

#2320 Remove review trigger and group github-{BDW,H100,MI201} under github-AT2
  .github/workflows/at2.yml
  .github/workflows/bdw.yml
  .github/workflows/h100.yml
  .github/workflows/mi210.yml
  .github/workflows/spr.yml
Labels: AT: WIP, AT2-SPECIAL-APPROVAL

#2318 coo2csr: add parens to function calls
  sparse/src/KokkosSparse_coo2crs.hpp
Labels: bug, Cleanup
