Repository kokkos/kokkos-kernels, pull requests merged in 2024-02, with the labels that each got.

#2094 Hands off namespace `Kokkos::Impl` - cleanup couple violations that snuck in
  batched/KokkosBatched_Util.hpp
  sparse/impl/KokkosSparse_coo2crs_impl.hpp
Labels: Cleanup

#2103 Lapack: adding svd benchmark
  lapack/unit_test/Test_Lapack_svd.hpp
  perf_test/CMakeLists.txt
  perf_test/lapack/CMakeLists.txt
  perf_test/lapack/KokkosLapack_SVD_benchmark.cpp
Labels: Cleanup

#2107 Lapack - SVD: adding quick return when cuSOLVER is skipped
  lapack/unit_test/Test_Lapack_svd.hpp
Labels: bug, Cleanup

#2110 Lapack - SVD: fix for unit-test when MKL is enabled
  blas/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
  lapack/unit_test/Test_Lapack_svd.hpp
Labels: bug, Cleanup

#2113 Fix for missing STL inclusion
  example/wiki/sparse/KokkosSparse_wiki_bsrmatrix.cpp
Labels: AT: PRE-TEST INSPECTED, TrilinosPatchMatch

#2112 BLAS - MKL: fixing HostBlas calls to handle MKL_INT type
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
Labels: bug, Cleanup

#2118 Update changelog 4.2.1
  CHANGELOG.md
Labels: AT: WIP

#2122 Wiki examples for BLAS2 functions are added
  blas/src/KokkosBlas2_ger.hpp
  blas/src/KokkosBlas2_syr.hpp
  blas/src/KokkosBlas2_syr2.hpp
  example/wiki/CMakeLists.txt
  example/wiki/blas/CMakeLists.txt
  example/wiki/blas/KokkosBlas2_wiki_ger.cpp
  example/wiki/blas/KokkosBlas2_wiki_syr.cpp
  example/wiki/blas/KokkosBlas2_wiki_syr2.cpp
Labels: bug, enhancement, Cleanup
