Repository kokkos/kokkos-kernels, pull requests merged in 2024-10, with the labels that each got.

#2321 .github/workflows: Add remaining spr and bdw checks
  .github/workflows/at2.yml
  .github/workflows/bdw.yml
  .github/workflows/spr.yml
Labels: AT: WIP, AT2-SPECIAL-APPROVAL

#2317 Add KokkosKernels::eager_initialize() to common
  blas/CMakeLists.txt
  blas/tpls/KokkosBlas_Cuda_tpl.hpp
  blas/tpls/KokkosBlas_Magma_tpl.hpp
  blas/tpls/KokkosBlas_Rocm_tpl.hpp
  blas/tpls/KokkosBlas_magma.hpp
  blas/tpls/KokkosBlas_tpl_spec.hpp
  cmake/KokkosKernels_config.h.in
  cmake/kokkoskernels_components.cmake
  common/CMakeLists.txt
  common/src/KokkosKernels_EagerInitialize.cpp
  common/src/KokkosKernels_EagerInitialize.hpp
  common/unit_test/CMakeLists.txt
  common/unit_test/Test_Common_EagerInitialize.cpp
  lapack/tpls/KokkosLapack_Cuda_tpl.hpp
  lapack/tpls/KokkosLapack_Magma_tpl.hpp
  lapack/tpls/KokkosLapack_cusolver.hpp
  lapack/tpls/KokkosLapack_magma.hpp
  sparse/tpls/KokkosKernels_tpl_handles_decl.hpp
  sparse/tpls/KokkosKernels_tpl_handles_def.hpp
Labels: enhancement

#2354 `kk_is_gpu_exec_space()` -> `is_gpu_exec_space_v`
  batched/dense/impl/KokkosBatched_Gemm_Team_Internal.hpp
  batched/dense/impl/KokkosBatched_HostLevel_Gemm_Impl.hpp
  batched/dense/impl/KokkosBatched_Trsm_Team_Internal.hpp
  blas/impl/KokkosBlas1_axpby_unification_attempt_traits.hpp
  blas/impl/KokkosBlas2_gemv_impl.hpp
  blas/impl/KokkosBlas2_ger_impl.hpp
  blas/impl/KokkosBlas2_syr2_impl.hpp
  blas/impl/KokkosBlas2_syr_impl.hpp
  blas/impl/KokkosBlas3_gemm_spec.hpp
  blas/unit_test/Test_Blas2_ger.hpp
  blas/unit_test/Test_Blas2_syr.hpp
  blas/unit_test/Test_Blas2_syr2.hpp
  common/src/KokkosKernels_ExecSpaceUtils.hpp
  common/src/KokkosKernels_Sorting.hpp
  common/src/KokkosKernels_Utils.hpp
  common/unit_test/Test_Common_LowerBound.hpp
  common/unit_test/Test_Common_UpperBound.hpp
  graph/impl/KokkosGraph_Distance2MIS_impl.hpp
  graph/src/KokkosGraph_CoarsenConstruct.hpp
  graph/src/KokkosGraph_Distance1ColorHandle.hpp
  perf_test/graph/KokkosGraph_triangle.cpp
  perf_test/sparse/KokkosSparse_block_pcg.cpp
  perf_test/sparse/KokkosSparse_par_ilut.cpp
  sparse/impl/KokkosSparse_bspgemm_impl.hpp
  sparse/impl/KokkosSparse_bspgemm_impl_kkmem.hpp
  sparse/impl/KokkosSparse_bspgemm_impl_speed.hpp
  sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  sparse/impl/KokkosSparse_spadd_symbolic_impl.hpp
  sparse/impl/KokkosSparse_spgemm_impl.hpp
  sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
  sparse/impl/KokkosSparse_spgemm_impl_def.hpp
  sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp
  sparse/impl/KokkosSparse_spgemm_impl_speed.hpp
  sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp
  sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp
  sparse/impl/KokkosSparse_spgemm_impl_triangle_no_compression.hpp
  sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
  sparse/impl/KokkosSparse_spmv_impl.hpp
  sparse/impl/KokkosSparse_spmv_impl_merge.hpp
  sparse/impl/KokkosSparse_spmv_struct_impl.hpp
  sparse/src/KokkosSparse_SortCrs.hpp
  sparse/src/KokkosSparse_Utils.hpp
  sparse/src/KokkosSparse_gauss_seidel_handle.hpp
  sparse/src/KokkosSparse_spgemm_handle.hpp
  sparse/unit_test/Test_Sparse_bspgemm.hpp
  sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Labels: Cleanup

#2345 Fix #2344: SVD hanging
  batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp
  batched/dense/unit_test/Test_Batched_SerialSVD.hpp
Labels: bug

#2357 workflow: adding permissions in workflow files
  .github/workflows/bdw.yml
  .github/workflows/h100.yml
  .github/workflows/mi210.yml
  .github/workflows/spr.yml
Labels: AT2-SPECIAL-APPROVAL

#2353 Don't use bulk sort in KokkosSparse::sort_crs_matrix sometimes
  sparse/impl/KokkosSparse_sort_crs_impl.hpp
  sparse/src/KokkosSparse_SortCrs.hpp
Labels: performance, TrilinosPatchMatch

#2355 Fix set-but-unused in Test_ODE_BDF
  ode/unit_test/Test_ODE_BDF.hpp
Labels: Cleanup

#2346 sparse_sort_crs: fix column shuffle indices
  perf_test/sparse/KokkosSparse_sort_crs.cpp
Labels: bug

#2361 workflows: fixing some action versions using current sha
  .github/workflows/bdw.yml
  .github/workflows/mi210.yml
Labels: AT2-SPECIAL-APPROVAL

#2356 Workflow volta70
  .github/workflows/at2.yml
  .github/workflows/volta70.yml
Labels: AT: WIP, AT2-SPECIAL-APPROVAL

#2369 workflows: fixing dependency for checkout action in volta70.yml
  .github/workflows/bdw.yml
  .github/workflows/volta70.yml
Labels: Cleanup, AT2-SPECIAL-APPROVAL

#2380 set `KokkosKernels_ENABLE_COMPONENT` variables to value instead of variable name
  cmake/kokkoskernels_components.cmake
Labels: bug

#2382 Do not specify template argument when using Kokkos atomics
  common/src/KokkosKernels_HashmapAccumulator.hpp
  graph/impl/KokkosGraph_Distance1Color_impl.hpp
  graph/impl/KokkosGraph_ExplicitCoarsening_impl.hpp
Labels: Cleanup

#2384 Blas1 asum: workaround for openblas error with short vectors
  blas/tpls/KokkosBlas_Host_tpl.cpp
Labels: bug

#2383 Prefer `atomic_assign(ptr, val) -> atomic_store(ptr, val)`
  common/unit_test/Test_Common_float128.hpp
  sparse/src/KokkosSparse_BsrMatrix.hpp
  sparse/src/KokkosSparse_CrsMatrix.hpp
Labels: Cleanup

#2386 Replace atomic_{inc, dec}[rement]
  graph/impl/KokkosGraph_Distance2MIS_impl.hpp
  graph/impl/KokkosGraph_ExplicitCoarsening_impl.hpp
  sparse/impl/KokkosSparse_bspgemm_impl_kkmem.hpp
  sparse/impl/KokkosSparse_partitioning_impl.hpp
  sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp
  sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
Labels: Cleanup

#2385 perf_tests: remove false dependence on google test
  batched/dense/unit_test/Test_Batched_SerialGemm.hpp
  batched/dense/unit_test/Test_Batched_SerialSVD.hpp
  blas/unit_test/Test_Blas2_gemv.hpp
  perf_test/CMakeLists.txt
  perf_test/KokkosKernels_perf_test_utilities.hpp
  perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test.cpp
  perf_test/blas/blas1/KokkosBlas_dot_perf_test.cpp
  perf_test/blas/blas1/KokkosBlas_team_dot_perf_test.cpp
  perf_test/blas/blas1/KokkosBlas_team_dot_perf_test_benchmark.cpp
  perf_test/blas/blas2/KokkosBlas2_gemv_perf_test.cpp
  perf_test/blas/blas2/KokkosBlas2_gemv_perf_test_benchmark.cpp
  perf_test/blas/blas2/KokkosBlas2_ger_perf_test_benchmark.cpp
  perf_test/blas/blas3/CMakeLists.txt
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test.cpp
  perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test_benchmark.cpp
  perf_test/graph/KokkosGraph_color.cpp
  perf_test/graph/KokkosGraph_color_d2.cpp
  perf_test/graph/KokkosGraph_mis_d2.cpp
  perf_test/graph/KokkosGraph_triangle.cpp
  perf_test/lapack/KokkosLapack_SVD_benchmark.cpp
  perf_test/ode/KokkosODE_BDF.cpp
  perf_test/ode/KokkosODE_RK.cpp
  perf_test/sparse/CMakeLists.txt
  perf_test/sparse/KokkosSparse_block_pcg.cpp
  perf_test/sparse/KokkosSparse_gs.cpp
  perf_test/sparse/KokkosSparse_mdf.cpp
  perf_test/sparse/KokkosSparse_pcg.cpp
  perf_test/sparse/KokkosSparse_spadd.cpp
  perf_test/sparse/KokkosSparse_spgemm.cpp
  perf_test/sparse/KokkosSparse_spgemm_jacobi.cpp
  perf_test/sparse/KokkosSparse_spmv_benchmark.cpp
  sparse/unit_test/Test_Sparse_gauss_seidel.hpp
  test_common/KokkosKernels_TestMatrixUtils.hpp
  test_common/KokkosKernels_TestStringUtils.hpp
  test_common/KokkosKernels_TestUtils.hpp
  test_common/KokkosKernels_TestVanilla.hpp
Labels: Cleanup

#2387 Prefer `expected == atomic_compare_exchange(ptr, expected, desired)`
  common/src/KokkosKernels_HashmapAccumulator.hpp
  common/src/KokkosKernels_Uniform_Initialized_MemoryPool.hpp
  graph/impl/KokkosGraph_ExplicitCoarsening_impl.hpp
  graph/src/KokkosGraph_CoarsenHeuristics.hpp
  sparse/impl/KokkosSparse_bspgemm_impl_kkmem.hpp
  sparse/impl/KokkosSparse_partitioning_impl.hpp
  sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
  sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp
  sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
Labels: Cleanup, BlocksPromotion

#2389 workflows: adding variable to set kokkos version to test against
  .github/workflows/at2.yml
  .github/workflows/bdw.yml
  .github/workflows/h100.yml
  .github/workflows/mi210.yml
  .github/workflows/osx.yml
  .github/workflows/spr.yml
  .github/workflows/volta70.yml
Labels: AT2-SPECIAL-APPROVAL

#2397 Fixing potential overflow issue in inner product trait
  batched/dense/impl/KokkosBatched_HostLevel_Gemm_DblBuf_Impl.hpp
  common/src/Kokkos_InnerProductSpaceTraits.hpp
  sparse/src/KokkosSparse_BsrMatrix.hpp
  sparse/src/KokkosSparse_spmv.hpp
  sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Labels: bug

#2405 Mult result conversion
  graph/impl/KokkosGraph_Distance2Color_impl.hpp
  sparse/src/KokkosSparse_IOUtils.hpp
  sparse/src/KokkosSparse_Utils.hpp
  sparse/src/KokkosSparse_sptrsv_supernode.hpp
Labels: bug, Cleanup

#2409 Fix potential overflow issue in spiluk
  sparse/unit_test/Test_Sparse_spiluk.hpp
Labels: bug, Cleanup

#2410 SerialInverseLU: fix overflow in integer multiplication
  batched/dense/unit_test/Test_Batched_SerialInverseLU.hpp
Labels: bug, Cleanup
