Repository kokkos/kokkos-kernels, pull requests merged in 2024-06, with the labels that each got.

#2230 README: adding link to scorecard
  README.md
Labels: Documentation

#2239 Graph: removing executable from repo
  example/graph/PartitioningExample
Labels: Cleanup

#2228 Sparse - BsrMatrix: adding new wiki example for documentation
  example/wiki/sparse/CMakeLists.txt
  example/wiki/sparse/KokkosSparse_wiki_bsrmatrix_2.cpp
Labels: enhancement, Documentation

#2242 Sparse - CrsToBsr: fix type mismatch
  sparse/impl/KokkosSparse_crs_to_bsr_impl.hpp
Labels: Cleanup

#2202 Add batched serial tbsv
  batched/dense/impl/KokkosBatched_Tbsv_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Tbsv_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Tbsv.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_DenseUtils.hpp
  batched/dense/unit_test/Test_Batched_SerialTbsv.hpp
  batched/dense/unit_test/Test_Batched_SerialTbsv_Complex.hpp
  batched/dense/unit_test/Test_Batched_SerialTbsv_Real.hpp
  blas/impl/KokkosBlas_util.hpp
Labels: feature request

#2252 Fix warning about memcpy
  common/src/KokkosKernels_BlockUtils.hpp
Labels: Cleanup

#2254 RCM fixes, improvements
  graph/impl/KokkosGraph_BFS_impl.hpp
  graph/unit_test/Test_Graph_rcm.hpp
Labels: bug, enhancement
