Repository kokkos/kokkos-kernels, pull requests merged in 2024-09, with the labels that each got.

#2322 implement batched serial pbtrf
  batched/dense/impl/KokkosBatched_Pbtrf_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Pbtrf_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Pbtrf.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_DenseUtils.hpp
  batched/dense/unit_test/Test_Batched_SerialPbtrf.hpp
  batched/dense/unit_test/Test_Batched_SerialPbtrf_Complex.hpp
  batched/dense/unit_test/Test_Batched_SerialPbtrf_Real.hpp
  blas/impl/KokkosBlas_util.hpp
Labels: feature request

#2327 [4.4.01] Patches to 4.4.01
  .github/workflows/at2.yml
  .github/workflows/bdw.yml
  .github/workflows/h100.yml
  .github/workflows/mi210.yml
  .github/workflows/release.yml
  .github/workflows/spr.yml
  CHANGELOG.md
  cmake/kokkoskernels_eti_offsets.cmake
  common/src/KokkosKernels_SimpleUtils.hpp
  common/src/KokkosKernels_Utils.hpp
  master_history.txt
  perf_test/sparse/CMakeLists.txt
  perf_test/sparse/KokkosSparse_sort_crs.cpp
  sparse/impl/KokkosSparse_sort_crs_impl.hpp
  sparse/src/KokkosSparse_SortCrs.hpp
  sparse/src/KokkosSparse_Utils.hpp
  sparse/src/KokkosSparse_coo2crs.hpp
  sparse/src/KokkosSparse_spadd_handle.hpp
Labels: AT2-SPECIAL-APPROVAL

#2333 remove unneeded volatile qualifier for Kokkos::Single
  sparse/impl/KokkosSparse_bspgemm_impl_kkmem.hpp
Labels: Cleanup

#2329 AT-2: adding non-TPL build for HIP backend
  .github/workflows/mi210.yml
Labels: AT: WIP, AT2-SPECIAL-APPROVAL

#2337 Master release 4.4.01
  .github/workflows/at2.yml
  .github/workflows/bdw.yml
  .github/workflows/h100.yml
  .github/workflows/mi210.yml
  .github/workflows/release.yml
  .github/workflows/spr.yml
  CHANGELOG.md
  CMakeLists.txt
  cmake/kokkoskernels_eti_offsets.cmake
  common/src/KokkosKernels_SimpleUtils.hpp
  common/src/KokkosKernels_Utils.hpp
  master_history.txt
  perf_test/sparse/CMakeLists.txt
  perf_test/sparse/KokkosSparse_sort_crs.cpp
  sparse/impl/KokkosSparse_sort_crs_impl.hpp
  sparse/src/KokkosSparse_SortCrs.hpp
  sparse/src/KokkosSparse_Utils.hpp
  sparse/src/KokkosSparse_coo2crs.hpp
  sparse/src/KokkosSparse_spadd_handle.hpp
Labels: AT2-SPECIAL-APPROVAL

#2340 Update changelog for 4.4.01
  CHANGELOG.md
Labels: AT: WIP
