Repository kokkos/kokkos-kernels, pull requests merged in 2024-05, with the labels that each got.

#2199 docs.yml: change kokkos version to latest release
  .github/workflows/docs.yml
Labels: AT: WIP

#2198 update changelog for 4.3.1
  CHANGELOG.md
Labels: AT: WIP

#2193 Sparse - SpGEMM: labeling spgemm_symbolic in TPL layer
  sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_decl.hpp
Labels: Cleanup

#2206 Disable cuBLAS dot wrapper
  blas/tpls/KokkosBlas1_dot_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_dot_tpl_spec_decl.hpp
Labels: performance

#2204 Fix spmv regressions
  sparse/impl/KokkosSparse_spmv_spec.hpp
  sparse/src/KokkosSparse_spmv.hpp
  sparse/src/KokkosSparse_spmv_handle.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: performance, TrilinosPatchMatch

#2210 Enable 3 at2 builds
  .github/workflows/bdw.yml
  .github/workflows/h100.yml
  .github/workflows/mi210.yml
Labels: AT: WIP, AT2-SPECIAL-APPROVAL

#2220 Kokkos Kernels: initial security policy
  .github/SECURITY.md
Labels: Documentation, AT: WIP

#2221 Kokkos Kernels: adding SHA for github actions
  .github/workflows/bdw.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/h100.yml
  .github/workflows/mi210.yml
  .github/workflows/osx.yml
  .github/workflows/spr.yml
  scripts/docker/Dockerfile.hip
  scripts/docker/Dockerfile.sycl
Labels: Cleanup, AT: WIP, AT2-SPECIAL-APPROVAL

#2222 More dependencies fix
  .github/workflows/osx.yml
  scripts/docker/Dockerfile.hip
  scripts/docker/Dockerfile.sycl
Labels: AT2-SPECIAL-APPROVAL

#2219 SPMV TPLs: improve profile region labels
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
Labels: enhancement
