Repository kokkos/kokkos-kernels, pull requests merged in 2024-03, with the labels that each got.

#2132 Fix2130
  sparse/src/KokkosSparse_spmv.hpp
  sparse/src/KokkosSparse_spmv_handle.hpp
Labels: bug, bug develop-only

#2135 Benchmark: modifying spmv benchmark to fix interface and run range of spmv tests
  perf_test/sparse/KokkosSparse_spmv_benchmark.cpp
Labels: Cleanup

#2133 Kokkos Kernels: update version guards to drop old version of Kokkos
  batched/KokkosBatched_Util.hpp
  batched/dense/impl/KokkosBatched_HostLevel_Gemm_Impl.hpp
  batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp
  common/impl/KokkosKernels_ViewUtils.hpp
  sparse/impl/KokkosSparse_coo2crs_impl.hpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_impl_v42.hpp
  sparse/src/KokkosSparse_coo2crs.hpp
  sparse/unit_test/Test_Sparse.hpp
Labels: Cleanup

#1930 ODE: BDF methods
  batched/dense/impl/KokkosBatched_Gesv_Impl.hpp
  batched/dense/src/KokkosBatched_Gesv.hpp
  ode/impl/KokkosODE_BDF_impl.hpp
  ode/impl/KokkosODE_Newton_impl.hpp
  ode/src/KokkosODE_BDF.hpp
  ode/src/KokkosODE_Newton.hpp
  ode/src/KokkosODE_Types.hpp
  ode/unit_test/Test_ODE.hpp
  ode/unit_test/Test_ODE_BDF.hpp
  ode/unit_test/Test_ODE_Newton.hpp
  perf_test/ode/CMakeLists.txt
  perf_test/ode/KokkosODE_BDF.cpp
Labels: bug, feature request, Cleanup

#2134 Sparse MKL: changing the location of the MKL_SAFE_CALL macro
  sparse/eti/generated_specializations_cpp/spmv/KokkosSparse_spmv_bsrmatrix_eti_spec_inst.cpp.in
  sparse/eti/generated_specializations_cpp/spmv/KokkosSparse_spmv_mv_bsrmatrix_eti_spec_inst.cpp.in
  sparse/eti/generated_specializations_hpp/KokkosSparse_spmv_bsrmatrix_eti_spec_avail.hpp.in
  sparse/eti/generated_specializations_hpp/KokkosSparse_spmv_mv_bsrmatrix_eti_spec_avail.hpp.in
  sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
  sparse/src/KokkosSparse_Utils_mkl.hpp
  sparse/src/KokkosSparse_spmv.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
Labels: Cleanup, AT: STALE

#2140 Kokkos Kernels: change the default offset ETI from size_t to int
  cmake/kokkoskernels_eti_offsets.cmake
Labels: enhancement, feature request

#2141 Fix usage of RAII to set cusparse/rocsparse stream
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: bug, AT: RETEST

#2136 Use execution space operator==
  sparse/src/KokkosSparse_spmv_handle.hpp
Labels: Cleanup, AT: RETEST

#2144 KokkosSparse_spmv_bsrmatrix_spec: fix Bsr_TC_Precision namespacing
  sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
Labels: bug

#2146 Spmv perftest improvements
  perf_test/sparse/KokkosSparse_kk_spmv.cpp
Labels: enhancement

#2152 SPMV tpl fixes, cusparse workaround
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
  sparse/unit_test/Test_Sparse_spmv.hpp
Labels: bug, enhancement

#2147 KokkosKernels Utils: cleaning the zero_vector interface
  common/src/KokkosKernels_Utils.hpp
  sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
Labels: Cleanup

#2139 Kokkos 4.2.00 minimum: Removing old code branch ahead of 4.3.00
  batched/dense/impl/KokkosBatched_Axpy_Impl.hpp
  batched/dense/impl/KokkosBatched_Copy_Impl.hpp
  batched/dense/impl/KokkosBatched_Dot_Internal.hpp
  batched/dense/impl/KokkosBatched_Gesv_Impl.hpp
  batched/dense/impl/KokkosBatched_HadamardProduct_Impl.hpp
  batched/dense/impl/KokkosBatched_Xpay_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_Serial_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_Team_Impl.hpp
  batched/sparse/src/KokkosBatched_JacobiPrec.hpp
  blas/src/KokkosBlas1_nrm2.hpp
  blas/unit_test/Test_Blas2_ger.hpp
  blas/unit_test/Test_Blas2_syr.hpp
  common/src/KokkosKernels_Error.hpp
  common/src/KokkosKernels_Half.hpp
  common/src/KokkosKernels_SimpleUtils.hpp
  common/src/Kokkos_ArithTraits.hpp
  common/unit_test/Test_Common_ArithTraits.hpp
  common/unit_test/Test_Common_LowerBound.hpp
  common/unit_test/Test_Common_UpperBound.hpp
  ode/impl/KokkosODE_Newton_impl.hpp
  sparse/src/KokkosSparse_spmv_team.hpp
  sparse/unit_test/Test_Sparse_spmv.hpp
  test_common/KokkosKernels_TestUtils.hpp
Labels: Cleanup

#2148 Update changelog for 4.3.00
  CHANGELOG.md
Labels: AT: WIP

#2160 spmv tpls: use correct bool for eti template param
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Labels: Cleanup
