Repository kokkos/kokkos-kernels, pull requests merged in 2024-01, with the labels that each got.

#2081 Axpby using less deep copy (solves issue #2080)
  blas/impl/KokkosBlas1_axpby_unification_attempt_traits.hpp
  blas/src/KokkosBlas1_axpby.hpp
Labels: AT: STALE

#2079 Add HIPManagedSpace support
  cmake/KokkosKernels_config.h.in
  cmake/kokkoskernels_eti_devices.cmake
  common/src/KokkosKernels_ExecSpaceUtils.hpp
  graph/unit_test/Test_Graph_graph_color.hpp
  sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
  test_common/Test_HIP.hpp
Labels: enhancement, AT: STALE

#1962 Add CUDA/HIP TPL support for KokkosSparse::spadd
  perf_test/sparse/KokkosSparse_spadd.cpp
  sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp
  sparse/impl/KokkosSparse_spadd_numeric_impl.hpp
  sparse/impl/KokkosSparse_spadd_numeric_spec.hpp
  sparse/impl/KokkosSparse_spadd_symbolic_impl.hpp
  sparse/impl/KokkosSparse_spadd_symbolic_spec.hpp
  sparse/src/KokkosKernels_Handle.hpp
  sparse/src/KokkosSparse_spadd.hpp
  sparse/src/KokkosSparse_spadd_handle.hpp
  sparse/tpls/KokkosSparse_spadd_numeric_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spadd_symbolic_tpl_spec_decl.hpp
  sparse/tpls/KokkosSparse_spadd_tpl_spec_avail.hpp
  sparse/tpls/KokkosSparse_spadd_tpl_spec_decl.hpp
  sparse/unit_test/Test_Sparse_spadd.hpp
Labels: enhancement, AT: PRE-TEST INSPECTED
