Repository kokkos/kokkos-kernels, pull requests merged in 2024-12, with the labels that each got.

#2444 Sptrsv stream test fixes
  sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
  sparse/src/KokkosSparse_sptrsv_handle.hpp
  sparse/unit_test/Test_Sparse_sptrsv.hpp
Labels: AT: PRE-TEST INSPECTED, AT2-CI-APPROVAL

#2419 Adopt `Kokkos::StaticCrsGraph` from "Core" and move `Static{Ccs,Crs}Graph` to namespace `KokkosSparse::`
  graph/unit_test/Test_Graph_rcm.hpp
  perf_test/graph/KokkosGraph_triangle.cpp
  perf_test/sparse/KokkosSparse_spmv_struct.cpp
  perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp
  perf_test/sparse/KokkosSparse_spmv_test.cpp
  sparse/src/KokkosSparse_BsrMatrix.hpp
  sparse/src/KokkosSparse_CcsMatrix.hpp
  sparse/src/KokkosSparse_CrsMatrix.hpp
  sparse/src/KokkosSparse_StaticCcsGraph.hpp
  sparse/src/KokkosSparse_StaticCrsGraph.hpp
  sparse/unit_test/Test_Sparse.hpp
  sparse/unit_test/Test_Sparse_StaticCrsGraph.hpp
Labels: AT2-CI-APPROVAL

#2452 Improve batched serial trsv
  batched/dense/impl/KokkosBatched_Trsv_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Trsv_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Trsv_Decl.hpp
  batched/dense/unit_test/Test_Batched_SerialTrsv.hpp
  batched/dense/unit_test/Test_Batched_SerialTrsv_Complex.hpp
  batched/dense/unit_test/Test_Batched_SerialTrsv_Real.hpp
Labels: AT: PRE-TEST INSPECTED, AT2-CI-APPROVAL

#2457 Workaround issue #2455
  sparse/src/KokkosSparse_StaticCrsGraph.hpp
Labels: bug

#2458 fix: alias for serial trsv
  batched/dense/src/KokkosBatched_Trsv_Decl.hpp
Labels: AT2-CI-APPROVAL

#2460 Fix the package version
  CMakeLists.txt
Labels: bug, Cleanup, AT2-CI-APPROVAL

#2461 Deprecated remarks to trsv serial impl
  batched/dense/impl/KokkosBatched_Trsv_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Trsv_Decl.hpp
Labels: bug, AT2-CI-APPROVAL

#2334 Fix unit test headers installation
  batched/CMakeLists.txt
  batched/dense/unit_test/CMakeLists.txt
  batched/sparse/unit_test/CMakeLists.txt
  common/CMakeLists.txt
  common/unit_test/CMakeLists.txt
  ode/CMakeLists.txt
  ode/unit_test/CMakeLists.txt
Labels: Cleanup, AT2-CI-APPROVAL

#2464 Allow dyn-rank-view in serial trsv
  batched/dense/impl/KokkosBatched_Trsv_Serial_Impl.hpp
  batched/dense/unit_test/Test_Batched_SerialTrsv.hpp
Labels: bug, Cleanup, AT2-CI-APPROVAL

#2468 Release 4.5.01
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  CHANGELOG.md
  CMakeLists.txt
  master_history.txt
Labels: AT2-SPECIAL-APPROVAL, AT2-CI-APPROVAL

#2465 nrm1: assert vector accessibility
  blas/src/KokkosBlas1_nrm1.hpp
Labels: Cleanup
