Repository kokkos/kokkos-kernels, pull requests merged in 2025-09, with the labels that each got.

#2700 Add setNumRows, setNumCols to sparse matrix structures
  docs/source/API/sparse-index.rst
  docs/source/API/sparse/CcsMatrix_constructors.rst
  docs/source/API/sparse/CooMatrix_constructors.rst
  docs/source/API/sparse/bsr_matrix.rst
  docs/source/API/sparse/ccs_matrix.rst
  docs/source/API/sparse/coo_matrix.rst
  docs/source/API/sparse/crs_matrix.rst
  scripts/check_api_updates.py
  sparse/src/KokkosSparse_BsrMatrix.hpp
  sparse/src/KokkosSparse_CcsMatrix.hpp
  sparse/src/KokkosSparse_CooMatrix.hpp
  sparse/src/KokkosSparse_CrsMatrix.hpp
Labels: enhancement

#2748 [Docs] batched serial pbtrf and pbtrs
  docs/source/API/batched-index.rst
  docs/source/API/batched/dense/batched_pbtrf.rst
  docs/source/API/batched/dense/batched_pbtrs.rst
Labels: Documentation

#2754 Move CUDA 12.0.0 jobs to 12.2.2
  .github/workflows/v100_kumquat.yml
Labels: AT2-SPECIAL-APPROVAL, CI: skip-docs

#2755 ci: drop H100 build from blake (same build on lychee)
  .github/workflows/at2.yml
  .github/workflows/h100.yml
Labels: AT2-SPECIAL-APPROVAL, CI: skip-docs

#2718 Drop deprecated double4 type for CUDA 13
  batched/dense/impl/KokkosBatched_Vector_SIMD_Arith.hpp
  batched/dense/src/KokkosBatched_Vector_SIMD.hpp
Labels: CompatibilityUpdate, AT2-CI-APPROVAL, CI: skip-docs

#2750 [Docs] List available batched dense functions in a table
  docs/source/API/batched/dense-index.rst
  docs/source/API/blas-index.rst
  docs/source/API/lapack-index.rst
Labels: Documentation

#2773 [Docs] batched serial ger
  docs/source/API/batched/dense-index.rst
  docs/source/API/batched/dense/batched_ger.rst
Labels: Documentation

#2787 [Docs] batched serial syr
  docs/source/API/batched/dense-index.rst
  docs/source/API/batched/dense/batched_ger.rst
  docs/source/API/batched/dense/batched_syr.rst
Labels: Documentation

#2789 [Docs] Add serial iamax example for documentation
  example/batched_solve/CMakeLists.txt
  example/batched_solve/serial_iamax.cpp
Labels: Documentation, AT2-CI-APPROVAL

#2786 Prefer bit manipulation functions from Kokkos Core
  common/src/KokkosKernels_BitUtils.hpp
Labels: Cleanup

#2797 [Docs] Add batched serial laswp example for documentation
  example/batched_solve/CMakeLists.txt
  example/batched_solve/serial_laswp.cpp
Labels: enhancement, Documentation, AT2-CI-APPROVAL
