Repository kokkos/kokkos-kernels, pull requests merged in 2025-05, with the labels that each got.

#2618 osx workflow: removing explicit parallelism levels
  .github/workflows/osx.yml
Labels: Cleanup, AT2-SPECIAL-APPROVAL, github_actions

#2568 sptrsv_cusparse: must call cusparseSpSV_analysis when matrix values have changed
  sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp
  sparse/src/KokkosSparse_sptrsv_handle.hpp
Labels: bug, AT2-CI-APPROVAL

#2620 Update changelog and workflow yml files for 4.6.01
  .github/workflows/at2.yml
  .github/workflows/codeql.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  CHANGELOG.md
Labels: AT2-SPECIAL-APPROVAL

#2614 Master release 4.6.01
  .github/workflows/at2.yml
  .github/workflows/codeql.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  CHANGELOG.md
  CMakeLists.txt
  docs/source/API/sparse-index.rst
  docs/source/API/sparse/par_ilut.rst
  master_history.txt
  sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp
  sparse/src/KokkosSparse_par_ilut.hpp
  sparse/src/KokkosSparse_par_ilut_handle.hpp
Labels: AT2-SPECIAL-APPROVAL

#2580 ConjTrans support for batched team gemm
  batched/KokkosBatched_Util.hpp
  batched/dense/impl/KokkosBatched_Gemm_Common_Impl.hpp
  batched/dense/impl/KokkosBatched_Gemm_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Gemm_Team_Impl.hpp
  batched/dense/impl/KokkosBatched_Gemm_Team_Internal.hpp
  batched/dense/impl/KokkosBatched_LU_Team_Internal.hpp
  batched/dense/impl/KokkosBatched_Trsm_Team_Internal.hpp
  batched/dense/src/KokkosBatched_Gemm_Decl.hpp
  batched/dense/unit_test/Test_Batched_TeamGemm.hpp
  batched/dense/unit_test/Test_Batched_TeamGemm_Complex.hpp
  batched/dense/unit_test/Test_Batched_TeamGemm_Real.hpp
Labels: enhancement, Cleanup, AT2-CI-APPROVAL, CI: skip-docs

#2621 Lapack - SVD: Unifying SVector layout to LayoutLeft
  docs/source/API/lapack/gesvd.rst
  lapack/src/KokkosLapack_svd.hpp
  lapack/tpls/KokkosLapack_svd_tpl_spec_avail.hpp
  lapack/tpls/KokkosLapack_svd_tpl_spec_decl.hpp
Labels: bug, feature request

#2638 [Documentation] Minor fixes
  docs/source/index.rst
  docs/source/quick_start.rst
Labels: Documentation

#2627 Port H100 PR test onto Lychee
  .github/workflows/at2.yml
  .github/workflows/h100_lychee.yml
Labels: AT2-SPECIAL-APPROVAL

#2634 Stride name fix
  batched/dense/impl/KokkosBatched_AddRadial_Impl.hpp
  batched/dense/impl/KokkosBatched_ApplyQ_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_ApplyQ_TeamVector_Impl.hpp
  batched/dense/impl/KokkosBatched_Axpy_Impl.hpp
  batched/dense/impl/KokkosBatched_Copy_Impl.hpp
  batched/dense/impl/KokkosBatched_Dot_Internal.hpp
  batched/dense/impl/KokkosBatched_Gbtrs_Serial_Internal.hpp
  batched/dense/impl/KokkosBatched_Gemm_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Gemm_TeamVector_Impl.hpp
  batched/dense/impl/KokkosBatched_Gemv_TeamVector_Impl.hpp
  batched/dense/impl/KokkosBatched_Gemv_Team_Impl.hpp
  batched/dense/impl/KokkosBatched_HadamardProduct_Impl.hpp
  batched/dense/impl/KokkosBatched_LU_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_LU_Team_Impl.hpp
  batched/dense/impl/KokkosBatched_Pbtrf_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Pbtrs_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_QR_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_QR_TeamVector_Impl.hpp
  batched/dense/impl/KokkosBatched_QR_WithColumnPivoting_TeamVector_Impl.hpp
  batched/dense/impl/KokkosBatched_SetIdentity_Impl.hpp
  batched/dense/impl/KokkosBatched_Tbsv_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Trmm_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Trsm_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Trsm_TeamVector_Impl.hpp
  batched/dense/impl/KokkosBatched_Trsm_Team_Impl.hpp
  batched/dense/impl/KokkosBatched_Trsv_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Trsv_TeamVector_Impl.hpp
  batched/dense/impl/KokkosBatched_Trsv_Team_Impl.hpp
  batched/dense/impl/KokkosBatched_Trtri_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Xpay_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_Serial_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp
  batched/sparse/impl/KokkosBatched_Spmv_Team_Impl.hpp
  batched/sparse/src/KokkosBatched_JacobiPrec.hpp
  blas/impl/KokkosBlas1_axpby_unification_attempt_traits.hpp
  blas/impl/KokkosBlas2_serial_gemv_impl.hpp
  blas/impl/KokkosBlas2_team_gemv_spec.hpp
  blas/src/KokkosBlas1_nrm2.hpp
  blas/src/KokkosBlas1_scal.hpp
  blas/tpls/KokkosBlas2_serial_gemv_tpl_spec_decl.hpp
  perf_test/batched/dense/do-not-use/KokkosBatched_Test_Gemm_Host.hpp
  perf_test/batched/dense/do-not-use/KokkosBatched_Test_Gemv_Host.hpp
  perf_test/batched/dense/do-not-use/KokkosBatched_Test_LU_Cuda.cpp
  perf_test/batched/dense/do-not-use/KokkosBatched_Test_LU_Host.hpp
  perf_test/batched/dense/do-not-use/KokkosBatched_Test_Trsm_Cuda.cpp
  perf_test/batched/dense/do-not-use/KokkosBatched_Test_Trsm_Host.hpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
  sparse/impl/KokkosSparse_spmv_team_spec.hpp
  sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
Labels: Cleanup, CI: skip-docs

#2642 Rename some reserved identifiers
  batched/dense/impl/KokkosBatched_HostLevel_Gemm_DblBuf_Impl.hpp
  batched/dense/impl/KokkosBatched_HostLevel_Gemm_Serial_Impl.hpp
Labels: Cleanup

#2640 Lapack - SVD: fixing build issue, will look at test tomorrow
  lapack/impl/KokkosLapack_svd_spec.hpp
  lapack/tpls/KokkosLapack_svd_tpl_spec_decl.hpp
  lapack/unit_test/Test_Lapack_svd.hpp
  ode/unit_test/Test_ODE_RK.hpp
Labels: bug, CI: skip-docs

#2641 Add CUDA 12.6.2 + compute sanitizer PR test
  .github/workflows/h100_lychee.yml
Labels: AT2-SPECIAL-APPROVAL

#2644 docs: testing literalinclude as proposed by Yuuichi
  docs/source/API/blas/blas1_dot.rst
  docs/source/API/blas/blas1_iamax.rst
  docs/source/API/blas/blas1_nrm1.rst
  docs/source/API/blas/blas1_nrm2.rst
  docs/source/API/blas/blas1_rot.rst
  docs/source/API/blas/blas1_rotg.rst
  docs/source/API/blas/blas1_rotm.rst
  docs/source/API/blas/blas1_rotmg.rst
  docs/source/API/blas/blas2_ger.rst
  docs/source/API/blas/blas2_syr.rst
  docs/source/API/blas/blas2_syr2.rst
  docs/source/API/graph/distance1_color.rst
  docs/source/API/graph/distance2_color.rst
  docs/source/API/sparse/bsr_matrix.rst
  docs/source/API/sparse/crs_matrix.rst
  docs/source/API/sparse/gauss_seidel_apply_backward.rst
  docs/source/API/sparse/gauss_seidel_apply_forward.rst
  docs/source/API/sparse/gauss_seidel_apply_symmetric.rst
  docs/source/API/sparse/gauss_seidel_numeric.rst
  docs/source/API/sparse/gauss_seidel_symbolic.rst
  docs/source/API/sparse/spadd_numeric.rst
  docs/source/API/sparse/spadd_symbolic.rst
  docs/source/API/sparse/spgemm_numeric.rst
  docs/source/API/sparse/spgemm_symbolic.rst
  docs/source/API/sparse/spmv.rst
Labels: Documentation, Cleanup

#2648 drop ROCm 5.6.1 PR test configs
  .github/workflows/at2.yml
  .github/workflows/mi210.yml
  .github/workflows/mi210_rocm621.yml
Labels: AT2-SPECIAL-APPROVAL

#2652 Remove redundant `ADD_LIBRARY(Kokkos::kokkoskernels)`
  CMakeLists.txt
Labels: bug, Cleanup

#2655 Add pttrf/pttrs example
  example/batched_solve/CMakeLists.txt
  example/batched_solve/serial_pttrs.cpp
Labels: AT2-CI-APPROVAL
