Repository kokkos/kokkos-kernels, pull requests merged in 2025-01, with the labels that each got.

#2466 Fixes while documenting
  blas/impl/KokkosBlas1_rot_impl.hpp
  blas/impl/KokkosBlas1_rot_spec.hpp
  blas/src/KokkosBlas1_rot.hpp
  blas/src/KokkosBlas1_rotg.hpp
  blas/src/KokkosBlas1_scal.hpp
  blas/src/KokkosBlas2_ger.hpp
  blas/src/KokkosBlas3_trmm.hpp
  blas/tpls/KokkosBlas1_rot_tpl_spec_avail.hpp
  blas/tpls/KokkosBlas1_rot_tpl_spec_decl.hpp
  blas/tpls/KokkosBlas_Host_tpl.cpp
  blas/tpls/KokkosBlas_Host_tpl.hpp
  blas/unit_test/Test_Blas1_rot.hpp
Labels: Cleanup

#2473 BLAS - ROT: calling appropriate cuBLAS function
  blas/tpls/KokkosBlas1_rot_tpl_spec_decl.hpp
Labels: bug, Cleanup

#2475 update changelog and readme to 4.5.1 with develop
  CHANGELOG.md
Labels: AT: WIP

#2469 Improve batched serial gemm
  batched/dense/impl/KokkosBatched_Gemm_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Gemm_Serial_Internal.hpp
  batched/dense/impl/KokkosBatched_Gemm_Team_Internal.hpp
  batched/dense/impl/KokkosBatched_InnerGemmFixC_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_LU_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Gemm_Decl.hpp
  batched/dense/src/KokkosBatched_InnerGemmFixC_Decl.hpp
  batched/dense/unit_test/Test_Batched_SerialGemm.hpp
  batched/dense/unit_test/Test_Batched_SerialGemm_Complex.hpp
  batched/dense/unit_test/Test_Batched_SerialGemm_Real.hpp
  blas/impl/KokkosBlas2_serial_gemv_inner_multiple_dot.hpp
  blas/impl/KokkosBlas_util.hpp
  common/src/KokkosKernels_BlockUtils.hpp
  sparse/impl/KokkosSparse_bspgemm_impl_seq.hpp
  sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
Labels: enhancement, AT2-CI-APPROVAL

#2331 implement batched serial getrf
  batched/dense/impl/KokkosBatched_Getrf_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Getrf_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Getrf.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_SerialGetrf.hpp
  blas/impl/KokkosBlas_util.hpp
Labels: feature request, AT2-CI-APPROVAL

#2483 implement batched serial getrs
  batched/dense/impl/KokkosBatched_Getrs_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Getrs_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Getrs.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_SerialGetrs.hpp
  blas/impl/KokkosBlas_util.hpp
Labels: enhancement, feature request, Cleanup, AT2-CI-APPROVAL
