Repository kokkos/kokkos-kernels, pull requests merged in 2025-06, with the labels that each got.

#2658 Rename remaining reserved identifiers in library
  batched/dense/impl/KokkosBatched_Trmm_Serial_Internal.hpp
  blas/impl/KokkosBlas3_trmm_impl.hpp
  common/src/KokkosKernels_BlockHashmapAccumulator.hpp
  graph/impl/KokkosGraph_Distance2MIS_impl.hpp
  lapack/impl/KokkosLapack_trtri_impl.hpp
  sparse/impl/KokkosSparse_bspgemm_impl.hpp
  sparse/impl/KokkosSparse_bspgemm_impl_speed.hpp
  sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp
  sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  sparse/impl/KokkosSparse_spgemm_impl.hpp
  sparse/impl/KokkosSparse_spgemm_impl_speed.hpp
  sparse/impl/KokkosSparse_spmv_impl_merge.hpp
  sparse/src/KokkosSparse_CrsMatrix.hpp
Labels: Cleanup, CI: skip-docs

#2668 Update license information in README.md
  README.md
Labels: Documentation, Cleanup, CI: skip-docs

#2663 Uses BLAS1 axpy execution space for internal deep_copy and fill operations
  blas/impl/KokkosBlas1_axpby_unification_attempt_traits.hpp
  blas/src/KokkosBlas1_axpby.hpp
Labels: CI: skip-docs

#2674 Don't lint deprecated macro
  batched/KokkosBatched_Util.hpp
Labels: Cleanup, CI: skip-docs

#2672 Add getrf-getrs example
  example/batched_solve/CMakeLists.txt
  example/batched_solve/serial_getrs.cpp
Labels: AT2-CI-APPROVAL

#2677 Rename reserved identifiers in `KokkosBatched_CG_TeamVector_Impl.hpp`
  batched/sparse/impl/KokkosBatched_CG_TeamVector_Impl.hpp
Labels: Cleanup, CI: skip-docs

#2685 Update partition_space() call to match Kokkos core changes
  sparse/unit_test/Test_Sparse_spmv.hpp
Labels: Cleanup, AT2-CI-APPROVAL

#2688 fix: constexpr condition to test long double complex type
  common/src/Kokkos_ArithTraits.hpp
Labels: bug, AT2-CI-APPROVAL, CI: skip-docs

#2669 SYCL: fixing issues revealed with icpx 2025
  blas/impl/KokkosBlas1_iamax_impl.hpp
  blas/unit_test/Test_Blas1_iamax.hpp
  sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
  sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp
Labels: bug, CompilerIssue, CI: skip-docs

#2690 trtri perf test: remove unused function
  perf_test/blas/blas3/KokkosBlas_trtri_perf_test.hpp
Labels: Cleanup

#2689 Batched: rename reserved identifiers
  batched/sparse/impl/KokkosBatched_GMRES_Serial_Impl.hpp
  batched/sparse/impl/KokkosBatched_GMRES_TeamVector_Impl.hpp
  batched/sparse/impl/KokkosBatched_GMRES_Team_Impl.hpp
  batched/sparse/src/KokkosBatched_Krylov_Handle.hpp
  batched/sparse/src/KokkosBatched_Krylov_Solvers.hpp
  perf_test/blas/blas1/KokkosBlas_perf_test.cpp
Labels: Cleanup, CI: skip-docs
