Repository kokkos/kokkos-kernels, pull requests merged in 2025-04, with the labels that each got.

#2579 docs: adding API documentation template
  docs/api_template.rst
Labels: feature request

#2617 Workflows: removing rocm 5.6.1 from at2
  .github/workflows/at2.yml
Labels: AT2-SPECIAL-APPROVAL

#2615 Avoid warning for explicit instantiations with storage class
  common/src/Kokkos_ArithTraits.hpp
Labels: CI: skip-docs
