Repository kokkos/kokkos-kernels, pull requests merged in 2025-03, with the labels that each got.

#2514 Remove old docker images
  scripts/docker/Dockerfile.hip
  scripts/docker/Dockerfile.sycl
Labels: Cleanup

#2523 docs: pinning github actions by SHA
  .github/workflows/docs.yml
Labels: AT2-SPECIAL-APPROVAL

#2524 docs: adding hashes for requirements.txt
  README.md
  docs/build_requirements.txt
Labels: enhancement, dependencies

#2525 Fixing issue with pragma unroll in laswp
  batched/dense/impl/KokkosBatched_Laswp_Serial_Internal.hpp
Labels: bug, Cleanup

#2527 docs: modifying the workflow to add --require-hases for pip
  .github/workflows/docs.yml
  README.md
  docs/build_requirements.txt
Labels: enhancement, Cleanup

#2504 Refactor batched serial pbtrs implementation details and tests
  batched/dense/src/KokkosBatched_Pbtrs.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_SerialPbtrs.hpp
  batched/dense/unit_test/Test_Batched_SerialPbtrs_Complex.hpp
  batched/dense/unit_test/Test_Batched_SerialPbtrs_Real.hpp
Labels: AT2-CI-APPROVAL

#2342 batched - dense: Testing and fixing Serial QR
  batched/KokkosBatched_Util.hpp
  batched/dense/impl/KokkosBatched_ApplyHouseholder_Serial_Internal.hpp
  batched/dense/impl/KokkosBatched_ApplyQ_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_ApplyQ_Serial_Internal.hpp
  batched/dense/impl/KokkosBatched_Householder_Serial_Internal.hpp
  batched/dense/impl/KokkosBatched_QR_FormQ_Serial_Internal.hpp
  batched/dense/impl/KokkosBatched_QR_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_QR_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_ApplyQ_Decl.hpp
  batched/dense/src/KokkosBatched_QR_Decl.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_SerialQR.hpp
  blas/impl/KokkosBlas_util.hpp
Labels: bug, enhancement

#2535 Sparse - sptrsv: Adjusting the perf test CUDA guard see issue #2428
  perf_test/sparse/KokkosSparse_sptrsv_aux.hpp
Labels: Cleanup

#2489 Implement batched serial gbtrf
  batched/dense/impl/KokkosBatched_Gbtrf_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Gbtrf_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Gbtrf.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_DenseUtils.hpp
  batched/dense/unit_test/Test_Batched_SerialGbtrf.hpp
  batched/dense/unit_test/Test_Batched_SerialPbtrf.hpp
  blas/impl/KokkosBlas_util.hpp
Labels: AT2-CI-APPROVAL

#2536 Add nightlyt tests on Frontier
  .gitlab/olcf-gitlab-ci.yml
Labels: enhancement, feature request

#2530 Refactor batched serial pttrf implementation details and tests
  batched/dense/impl/KokkosBatched_Pttrf_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Pttrf_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Pttrf.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_SerialPttrf.hpp
  batched/dense/unit_test/Test_Batched_SerialPttrf_Complex.hpp
  batched/dense/unit_test/Test_Batched_SerialPttrf_Real.hpp
Labels: Cleanup

#2552 update changelog for 4.6.0
  CHANGELOG.md
Labels: AT: WIP

#2554 rocTPLs: modifying cmake logic to prioritize find_package
  cmake/Modules/FindTPLROCBLAS.cmake
  cmake/Modules/FindTPLROCSOLVER.cmake
  cmake/Modules/FindTPLROCSPARSE.cmake
Labels: enhancement, feature request

#2559 Documentation changes enforcement
  .github/workflows/docs.yml
  lapack/src/KokkosLapack_trtri.hpp
  scripts/check_api_updates.py
Labels: feature request, CI: skip-docs

#2575 Skip docs
  .github/workflows/docs.yml
  blas/src/KokkosBlas3_gemm.hpp
Labels: AT2-SPECIAL-APPROVAL, CI: skip-docs

#2556 PR tests on ROCm 6.2.1
  .github/workflows/at2.yml
  .github/workflows/mi210_rocm621.yml
Labels: AT2-SPECIAL-APPROVAL

#2572 replace uses of get_suggested_vector__size with kk_get_suggested_vector_size
  common/src/KokkosKernels_Utils.hpp
  sparse/impl/KokkosSparse_spgemm_impl_memaccess.hpp
Labels: CI: skip-docs

#2571 rename _-prefixed include guards
  common/src/KokkosKernels_ExecSpaceUtils.hpp
  common/src/KokkosKernels_IOUtils.hpp
  common/src/KokkosKernels_SimpleUtils.hpp
  common/src/KokkosKernels_Utils.hpp
  graph/impl/KokkosGraph_BFS_impl.hpp
  graph/impl/KokkosGraph_Distance1Color_impl.hpp
  graph/impl/KokkosGraph_Distance2Color_impl.hpp
  graph/impl/KokkosGraph_Distance2MIS_impl.hpp
  graph/src/KokkosGraph_Distance1Color.hpp
  graph/src/KokkosGraph_Distance1ColorHandle.hpp
  graph/src/KokkosGraph_Distance2Color.hpp
  graph/src/KokkosGraph_Distance2ColorHandle.hpp
  graph/src/KokkosGraph_MIS2.hpp
  graph/src/KokkosGraph_RCM.hpp
  graph/src/KokkosGraph_Triangle.hpp
  sparse/impl/KokkosSparse_bspgemm_impl.hpp
  sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp
  sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
  sparse/impl/KokkosSparse_partitioning_impl.hpp
  sparse/impl/KokkosSparse_sort_crs_impl.hpp
  sparse/impl/KokkosSparse_spadd_numeric_impl.hpp
  sparse/impl/KokkosSparse_spadd_symbolic_impl.hpp
  sparse/impl/KokkosSparse_spgemm_impl.hpp
  sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp
  sparse/impl/KokkosSparse_twostage_gauss_seidel_impl.hpp
  sparse/src/KokkosKernels_Controls.hpp
  sparse/src/KokkosKernels_Handle.hpp
  sparse/src/KokkosSparse_IOUtils.hpp
  sparse/src/KokkosSparse_SortCrs.hpp
  sparse/src/KokkosSparse_Utils_rocsparse.hpp
  sparse/src/KokkosSparse_ccs2crs.hpp
  sparse/src/KokkosSparse_crs2ccs.hpp
  sparse/src/KokkosSparse_crs2coo.hpp
  sparse/src/KokkosSparse_gauss_seidel.hpp
  sparse/src/KokkosSparse_gauss_seidel_handle.hpp
  sparse/src/KokkosSparse_gmres_handle.hpp
  sparse/src/KokkosSparse_par_ilut_handle.hpp
  sparse/src/KokkosSparse_spadd.hpp
  sparse/src/KokkosSparse_spadd_handle.hpp
  sparse/src/KokkosSparse_spgemm.hpp
  sparse/src/KokkosSparse_spgemm_handle.hpp
  sparse/src/KokkosSparse_spgemm_jacobi.hpp
  sparse/src/KokkosSparse_spgemm_numeric.hpp
  sparse/src/KokkosSparse_spgemm_symbolic.hpp
  sparse/src/KokkosSparse_spiluk_handle.hpp
Labels: CI: skip-docs

#2539 Implement batched serial gbtrs
  batched/dense/impl/KokkosBatched_Gbtrs_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Gbtrs_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Gbtrs.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_SerialGbtrs.hpp
  blas/impl/KokkosBlas_util.hpp
Labels: feature request, AT2-CI-APPROVAL

#2574 KokkosKernels_HashmapAccumulator.hpp: rename reserved ids
  common/src/KokkosKernels_HashmapAccumulator.hpp
Labels: CI: skip-docs

#2577 remove _-prefixed include guard
  sparse/src/KokkosSparse_coo2crs.hpp
Labels: CI: skip-docs
