Repository kokkos/kokkos-kernels, pull requests merged in 2025-02, with the labels that each got.

#2492 SPRASE- SpADD: moving spadd out of experimental
  perf_test/sparse/KokkosSparse_spadd.cpp
  sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp
  sparse/src/KokkosSparse_spadd.hpp
  sparse/unit_test/Test_Sparse_spadd.hpp
Labels: Cleanup

#2493 Sparse - spgemm: moving symbolic and numeric phases out of the experimental namespace
  graph/src/KokkosGraph_CoarsenConstruct.hpp
  perf_test/sparse/KokkosSparse_run_spgemm_jacobi.hpp
  perf_test/sparse/KokkosSparse_spgemm.cpp
  sparse/impl/KokkosSparse_bspgemm_numeric_spec.hpp
  sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp
  sparse/impl/KokkosSparse_spgemm_jacobi_spec.hpp
  sparse/impl/KokkosSparse_spgemm_noreuse_spec.hpp
  sparse/src/KokkosSparse_spgemm.hpp
  sparse/src/KokkosSparse_spgemm_numeric.hpp
  sparse/src/KokkosSparse_spgemm_symbolic.hpp
  sparse/unit_test/Test_Sparse_spgemm.hpp
  sparse/unit_test/Test_Sparse_spgemm_jacobi.hpp
Labels: Cleanup

#2494 Sparse - Gauss Seidel: moving GS out of experimental namespace
  example/wiki/sparse/KokkosSparse_wiki_gauss_seidel.cpp
  perf_test/sparse/KokkosSparse_gs.cpp
  perf_test/sparse/KokkosSparse_pcg.hpp
  sparse/src/KokkosSparse_gauss_seidel.hpp
  sparse/unit_test/Test_Sparse_block_gauss_seidel.hpp
  sparse/unit_test/Test_Sparse_gauss_seidel.hpp
Labels: Cleanup

#2495 Iluk deprecate experimental
  perf_test/sparse/KokkosSparse_par_ilut.cpp
  perf_test/sparse/KokkosSparse_spiluk.cpp
  sparse/src/KokkosSparse_spiluk.hpp
  sparse/unit_test/Test_Sparse_spiluk.hpp
Labels: Cleanup

#2496 Sparse - SpTRSV: moving kenerls out of Experimental
  perf_test/sparse/KokkosSparse_sptrsv.cpp
  sparse/impl/KokkosSparse_twostage_gauss_seidel_impl.hpp
  sparse/src/KokkosSparse_LUPrec.hpp
  sparse/src/KokkosSparse_sptrsv.hpp
  sparse/src/KokkosSparse_sptrsv_supernode.hpp
  sparse/unit_test/Test_Sparse_sptrsv.hpp
Labels: Cleanup

#2497 Implement batched serial syr
  batched/dense/impl/KokkosBatched_Syr_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Syr_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Syr.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_SerialSyr.hpp
  blas/impl/KokkosBlas_util.hpp
Labels: AT2-CI-APPROVAL

#2500 Adding ctest config for cdash submissions
  CTestConfig.cmake
Labels: enhancement

#2499 implement batched serial lacgv
  batched/dense/impl/KokkosBatched_Lacgv_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Lacgv_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Lacgv.hpp
  batched/dense/unit_test/Test_Batched_Dense.hpp
  batched/dense/unit_test/Test_Batched_SerialLacgv.hpp
Labels: AT2-CI-APPROVAL

#2478 Refactor serial tbsv implementation details and tests
  batched/dense/impl/KokkosBatched_Pbtrs_Serial_Internal.hpp
  batched/dense/impl/KokkosBatched_Tbsv_Serial_Impl.hpp
  batched/dense/impl/KokkosBatched_Tbsv_Serial_Internal.hpp
  batched/dense/src/KokkosBatched_Tbsv.hpp
  batched/dense/unit_test/Test_Batched_SerialTbsv.hpp
  batched/dense/unit_test/Test_Batched_SerialTbsv_Complex.hpp
  batched/dense/unit_test/Test_Batched_SerialTbsv_Real.hpp
Labels: AT2-CI-APPROVAL

#2502 Worflow: refactoring SPR to standard cmake and suppress warnings
  .github/workflows/spr.yml
Labels: AT2-SPECIAL-APPROVAL

#2505 Batched svd stability
  batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp
  batched/dense/unit_test/Test_Batched_SerialSVD.hpp
Labels: bug

#2510 SYCL - SIMD: preventing AVX512 code to be compiled when targeting GPU
  batched/dense/src/KokkosBatched_Vector_SIMD.hpp
Labels: bug, Cleanup

#2506 SYCL: Fix Test_Common_AlignPtrTo.hpp
  common/unit_test/Test_Common_AlignPtrTo.hpp
Labels: AT2-CI-APPROVAL

#2511 Same fix as PR #2435 but rebased on develop
  cmake/KokkosKernelsConfig.cmake.in
Labels: enhancement, Cleanup
