Repository kokkos/kokkos-kernels, pull requests merged in 2025-08, with the labels that each got.

#2720 variety of reserved indentifier cleanups
  perf_test/batched/sparse/SPMV/KokkosBatched_Test_SPMV.cpp
  perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
  perf_test/blas/blas3/KokkosBlas_trtri_perf_test.hpp
  sparse/src/KokkosSparse_LUPrec.hpp
  sparse/src/KokkosSparse_MatrixPrec.hpp
  sparse/src/KokkosSparse_ccs2crs.hpp
  sparse/src/KokkosSparse_crs2ccs.hpp
Labels: Cleanup

#2730 Minor fix for coefficient type in SPMV_Functor
  sparse/impl/KokkosSparse_spmv_impl.hpp
Labels: bug

#2738 ci: Add V100 CUDA 12.6.2 build with TPLs
  .github/workflows/at2.yml
  .github/workflows/v100_kumquat.yml
  .github/workflows/volta70.yml
  blas/unit_test/Test_Blas2_ger.hpp
Labels: AT2-SPECIAL-APPROVAL, AT2-CI-APPROVAL, CI: skip-docs

#2678 [Docs] batched serial pttrf and pttrs
  docs/source/API/batched-index.rst
  docs/source/API/batched/dense-index.rst
  docs/source/API/batched/dense/batched_pttrf.rst
  docs/source/API/batched/dense/batched_pttrs.rst
  docs/source/API/batched/sparse-index.rst
Labels: Documentation
